- app/config/AppConfig.scala
- app/connectors/CustomsDeclarationsConnector.scala
- app/connectors/CustomsDeclareExportsConnector.scala
- app/controllers/NotificationsController.scala
- app/controllers/actions/AuthAction.scala
- app/models/Notification.scala
- app/models/Status.scala
- build.sbt
- conf/app.routes
- test/base/CustomExportsBaseSpec.scala
- test/base/ExportsTestData.scala
- test/base/MockAuthAction.scala
- test/base/MockConnectors.scala
- test/base/MockHttpClient.scala
- test/controllers/NotificationsControllerSpec.scala
- test/controllers/SimpleDeclarationControllerSpec.scala
- test/utils/EnumerableSpec.scala
[CEDS-647](https://jira.tools.tax.service.gov.uk/browse/CEDS-647)
> [CEDS-647] Added Controller for notification and correct tests with authentication

- app/controllers/CancelDeclarationController.scala
- app/forms/CancelDeclarationForm.scala
- app/views/supplementary/declarant_address.scala.html
Additionally, I used autoformat on two files.
> [CEDS-806] Fixed titles

- app/controllers/SimpleDeclarationController.scala
- app/forms/SimpleDeclarationForm.scala
- app/views/simpleDeclaration.scala.html
- app/views/submission_notifications.scala.html
- app/views/submissions.scala.html
Added correct date time format for submissions and notifications (only view)
Added possibility to add lrn and mrn during simple declaration.
PR related with PR from the backend app: https://github.com/hmrc/customs-declare-exports/pull/19
> CEDS-831 Added correct date time format and possibility to add mrn and lrn

- .scalafmt.conf
- app/controllers/RoleController.scala
- app/controllers/supplementary/ConsigneeAddressController.scala
- app/controllers/supplementary/DeclarationHolderController.scala
- app/controllers/supplementary/DestinationCountriesController.scala
- app/controllers/supplementary/RepresentativeDetailsPageController.scala
- app/forms/Choice.scala
- app/forms/MovementForms.scala
- app/forms/Role.scala
- app/forms/supplementary/AddressAndIdentification.scala
- app/forms/supplementary/DeclarationAdditionalActors.scala
- app/forms/supplementary/DeclarationHolder.scala
- app/forms/supplementary/DestinationCountries.scala
- app/views/role_page.scala.html
- app/views/supplementary/consignee_details.scala.html
- app/views/supplementary/consignor_details.scala.html
- app/views/supplementary/declarant_details.scala.html
- app/views/supplementary/declaration_additional_actors.scala.html
- app/views/supplementary/declaration_holder.scala.html
- app/views/supplementary/declaration_type.scala.html
- app/views/supplementary/destination_countries.scala.html
- app/views/supplementary/dispatch_location.scala.html
- app/views/supplementary/representative_details.scala.html
- conf/messages.en
- conf/supplementary.routes
- test/base/CustomExportsBaseSpec.scala
- test/controllers/supplementary/ConsigneeAddressControllerSpec.scala
- test/controllers/supplementary/DeclarationHolderControllerSpec.scala
- test/controllers/supplementary/DestinationCountriesControllerSpec.scala
- test/controllers/supplementary/RepresentativeDetailsPageControllerSpec.scala
[CEDS-891](https://jira.tools.tax.service.gov.uk/browse/CEDS-891)
[CEDS-874](https://jira.tools.tax.service.gov.uk/browse/CEDS-874)
[CEDS-822](https://jira.tools.tax.service.gov.uk/browse/CEDS-822)
[CEDS-770](https://jira.tools.tax.service.gov.uk/browse/CEDS-770)
Fixed back buttons for the supplementary journey
> CEDS-891 Add tariff codes to existing pages, Consignee address page, holder of authorisation, dispatch countries & back buttons

- app/controllers/supplementary/AdditionalInformationController.scala
- app/controllers/supplementary/PreviousDocumentsController.scala
- app/controllers/util/FormAction.scala
- app/controllers/util/MultipleItemsHelper.scala
- app/forms/supplementary/AdditionalInformation.scala
- app/forms/supplementary/Document.scala
- app/models/declaration/supplementary/AdditionalInformationData.scala
- app/models/declaration/supplementary/SupplementaryDeclarationData.scala
- app/views/supplementary/additional_information.scala.html
- app/views/supplementary/previous_documents.scala.html
- app/views/supplementary/summary/previous_documents_section.scala.html
- conf/messages.en
- test/controllers/supplementary/AdditionalInformationControllerSpec.scala
- test/controllers/supplementary/PreviousDocumentsControllerSpec.scala
- test/controllers/util/MultipleItemsHelperSpec.scala
- test/forms/supplementary/AdditionalInformationSpec.scala
- test/forms/supplementary/DocumentSpec.scala
- test/models/declaration/supplementary/SupplementaryDeclarationDataSpec.scala
DO NOT MERGE IT
I want to share the idea of the general approach. To presentation, I choose Additional Information page for now only Add method works, but please focus and check MultiplyItemHelper object.
Amount of code it's good shown inside PreviousDocumentsController and way how to handle it.
AdditionalInformation page has this solution but needs more changes to fix everything.
I'm waiting for feedback
> General approach of handling forms - implemented on AdditionalInformationPage

- test/controllers/supplementary/CommodityMeasureControllerSpec.scala
- test/controllers/supplementary/ExporterDetailsPageControllerSpec.scala
- test/controllers/supplementary/GoodsItemNumberControllerSpec.scala
- test/helpers/CommodityMeasureMessages.scala
- test/helpers/ExporterDetailsMessages.scala
- test/helpers/GoodItemNumberMessages.scala
- test/views/ConsigneeDetailsViewSpec.scala
- test/views/supplementary/CommodityMeasureViewSpec.scala
- test/views/supplementary/ConsignmentReferencesViewSpec.scala
- test/views/supplementary/ExporterDetailsViewSpec.scala
- test/views/supplementary/GoodItemNumberViewSpec.scala
- Added tests for CommodityMeasure, ExporterDetails and GoodsItemNumber views
> * CEDS-1002 Review Frontend tests

- app/controllers/declaration/ConsigneeDetailsPageController.scala
- app/controllers/declaration/ExporterDetailsPageController.scala
- app/forms/declaration/ConsigneeDetails.scala
- app/views/components/input_text_multiple_values.scala.html
- app/views/declaration/consignee_details.scala.html
- app/views/declaration/declarant_details.scala.html
- app/views/declaration/package_information.scala.html
- app/views/declaration/previous_documents.scala.html
- conf/messages.en
- test/controllers/declaration/ConsigneeDetailsPageControllerSpec.scala
- test/controllers/declaration/ExporterDetailsPageControllerSpec.scala
- test/forms/declaration/ConsigneeDetailsSpec.scala
- test/helpers/views/declaration/ConsigneeDetailsMessages.scala
- test/views/ConsigneeDetailsViewSpec.scala
- test/views/declaration/DeclarantDetailsViewSpec.scala
- test/views/declaration/spec/ViewSpec.scala
* Add 3/9, 3/10 Consignee details to the full journey
Implement the `toMetadataProperties` method
Update the view, form, controller and model
* Use '.button--secondary' class to grey out multiple item buttons
> Add 3/9, 3/10 Consignee details to the standard/full journey

- app/controllers/declaration/CarrierDetailsPageController.scala
- app/controllers/declaration/DeclarationAdditionalActorsController.scala
- app/controllers/declaration/RepresentativeDetailsPageController.scala
- app/forms/declaration/CarrierDetails.scala
- app/views/declaration/carrier_details.scala.html
- app/views/declaration/declaration_additional_actors.scala.html
- conf/declaration.routes
- conf/messages.en
- test/controllers/declaration/CarrierDetailsPageControllerSpec.scala
- test/controllers/declaration/RepresentativeDetailsPageControllerSpec.scala
- test/forms/declaration/CarrierDetailsSpec.scala
- test/helpers/views/declaration/CarrierDetailsMessages.scala
- test/views/declaration/CarrierDetailsViewSpec.scala
- test/views/declaration/ConsigneeDetailsViewSpec.scala
- test/views/declaration/DeclarationAdditionalActorsViewSpec.scala
- test/views/declaration/spec/ViewSpec.scala
* Move `ConsigneeDetailsViewSpec` inside `'test/views/declaration/'`
* Add 3/31, 3/32 Carrier details to the full journey
Implement the `toMetadataProperties` method
Update the view, form, controller and model
> CEDS-1024 Add 3/31, 3/32 Carrier details to the full journey

- test/controllers/ChoiceControllerSpec.scala
- test/controllers/StartControllerSpec.scala
- test/helpers/views/declaration/ChoiceMessages.scala
- test/helpers/views/declaration/StartMessages.scala
- test/views/ChoiceViewSpec.scala
- test/views/StartViewSpec.scala
- Added tests for Start, Choice views
> * CEDS-1002 Review Frontend tests *

- app/views/declaration/items_summary.scala.html
- test/views/declaration/ItemTypeViewSpec.scala
* **Fix test errors due to content changes**
This was caused due to a rebase conflict that was not spoted by myself.
This also hightlights the fact that humans will make errors from time to
time and we need to rely on Jenkins tests being run as part of pull
requests.
* **Fix internationalisation errors**
>  CEDS-1051 Fix test errors due to content changes

- app/forms/CancelDeclaration.scala
- app/forms/cancellation/CancellationChangeReason.scala
- app/views/cancel_declaration.scala.html
- app/views/components/input_radio_with_hint.scala.html
- conf/messages.en
- test/controllers/CancelDeclarationControllerSpec.scala
- test/forms/CancelDeclarationSpec.scala
- test/views/cancellation/CancelDeclarationViewSpec.scala
* This also included adding a Cancellation model spec class to test the
mapping was correct.
* I have also added a View spec class.
> CEDS-951 Add changeReason to Cancellation Model

- app/services/mapping/AuthorisationHoldersBuilder.scala
- test/services/mapping/AuthorisationHoldersBuilderSpec.scala
Added AuthorisationHoldersBuilder
> Ceds 1138 authorisationholders

- app/controllers/declaration/ItemsSummaryController.scala
- app/controllers/declaration/SummaryPageController.scala
- app/services/WcoMetadataMapper.scala
This is a fix, as we were duplicating the LNR twice.
> CEDS-1146 Capture the DUCR

- app/config/AppConfig.scala
- conf/application.conf
This is causing some errors when testing in the development environment.
We are simply trying to understand if this solves the issue
> CEDS-1146 Change the way the mapping-strategy is loaded

- app/views/declaration/items_summary.scala.html
Tests for this view were missing, I didn't add anything now, because whole items summary page be changed as next task.
> CEDS-1082 Change wrong back link

- app/config/AppConfig.scala
- app/controllers/declaration/ItemsSummaryController.scala
- app/views/declaration/items_summary.scala.html
- conf/messages.en
- test/config/AppConfigSpec.scala
On the items summary should be only general information about item and must it be in one row.
Ticket doesn't cover removing, editing, viewing all elements for an item.
> CEDS-1115 Changes for item summary page

- app/services/mapping/declaration/AgentBuilder.scala
- app/services/mapping/declaration/ExporterBuilder.scala
- app/services/mapping/goodsshipment/ConsigneeBuilder.scala
- app/services/mapping/goodsshipment/UCRBuilder.scala
- app/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilder.scala
- test/forms/common/AddressSpec.scala
- test/forms/declaration/ConsigneeDetailsSpec.scala
- test/forms/declaration/EntityDetailsSpec.scala
- test/forms/declaration/ExporterDetailsSpec.scala
- test/forms/declaration/RepresentativeDetailsSpec.scala
- test/services/mapping/declaration/AgentBuilderSpec.scala
- test/services/mapping/declaration/ExporterBuilderSpec.scala
- test/services/mapping/goodsshipment/ConsigneeBuilderSpec.scala
- test/services/mapping/goodsshipment/UCRBuilderSpec.scala
- test/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
* Do not create URC is DUCR is not supplied
* Do not set StatisicalAmount if `value` is not supplied
* Do not set NameType if Entity `fullname` not supplied
> CEDS-1146 Fix other mapping errors

- app/forms/common/Address.scala
- app/utils/validators/forms/FieldValidator.scala
- app/views/declaration/items_summary.scala.html
- conf/application.conf
- conf/messages.en
- test/forms/declaration/ConsigneeDetailsSpec.scala
- test/forms/declaration/ExporterDetailsSpec.scala
- test/services/mapping/goodsshipment/UCRBuilderSpec.scala
- test/utils/validators/forms/FieldValidatorSpec.scala
Second commit is about disabling auditing locally. If you want to stay with this we can remove this commit
> CEDS-1101 Add support for more characters in name fields

- app/controllers/declaration/RepresentativeDetailsPageController.scala
- app/forms/declaration/RepresentativeDetails.scala
- app/services/mapping/declaration/AgentBuilder.scala
- app/views/components/error_summary.scala.html
- app/views/declaration/summary/parties_section.scala.html
- build.sbt
- test/base/ViewValidator.scala
- test/controllers/declaration/RepresentativeDetailsPageControllerSpec.scala
- test/forms/declaration/RepresentativeDetailsSpec.scala
- test/views/declaration/RepresentativeDetailsViewSpec.scala
- test/views/declaration/summary/PartiesSectionViewSpec.scala
This commit covers making the page as optinal page with fixes for the tests.
Moreover I removed scalacOptions during compilation to give a possibility to use deprecated messages (now it's warning, not error)
Two helper methods for views are deprecated. We're trying to achieve using getElementById not Css - so it's first step.
> CEDS-1152 Change to optional page when user doesn't fill anything

- app/views/declaration/declaration_additional_actors.scala.html
This commit is for Declaration Additional Actors page only.
> CEDS-1203 Change ENTER key to trigger Add button instead of Remove pt.2

- app/services/mapping/declaration/consignment/DeclarationConsignmentBuilder.scala
- app/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilder.scala
- test/services/mapping/declaration/consignment/DeclarationConsignmentBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilderSpec.scala
This is just to be used in the Standard Journey
> CEDS-1224 Add Consignment.Carrier builder

- app/controllers/declaration/AdditionalDeclarationTypePageController.scala
- app/controllers/declaration/BorderTransportController.scala
- app/controllers/declaration/ConsigneeDetailsPageController.scala
- app/controllers/declaration/ConsignmentReferencesController.scala
- app/controllers/declaration/DeclarantDetailsPageController.scala
- app/controllers/declaration/DeclarationAdditionalActorsController.scala
- app/controllers/declaration/DeclarationHolderController.scala
- app/controllers/declaration/DispatchLocationPageController.scala
- app/controllers/declaration/ExporterDetailsPageController.scala
- app/controllers/declaration/RepresentativeDetailsPageController.scala
- app/controllers/declaration/TransportContainerController.scala
- app/controllers/declaration/TransportDetailsController.scala
- app/controllers/declaration/WarehouseIdentificationController.scala
- app/models/declaration/Parties.scala
- app/services/cache/ExportsCacheModelRepository.scala
- test/base/CustomExportsBaseSpec.scala
- test/controllers/declaration/BorderTransportControllerSpec.scala
- test/controllers/declaration/ConsigneeDetailsPageControllerSpec.scala
- test/controllers/declaration/DeclarantDetailsPageControllerSpec.scala
- test/controllers/declaration/DeclarationAdditionalActorsControllerSpec.scala
- test/controllers/declaration/DeclarationHolderControllerSpec.scala
- test/controllers/declaration/ExporterDetailsPageControllerSpec.scala
- test/controllers/declaration/ItemTypePageControllerSpec.scala
- test/controllers/declaration/RepresentativeDetailsPageControllerSpec.scala
- test/controllers/declaration/TransportDetailsControllerSpec.scala
- test/controllers/declaration/TransportInformationContainersPageControllerSpec.scala
- test/controllers/declaration/WarehouseIdentificationControllerSpec.scala
* Create 'Parties' section inside the Cache Model  …
* Add remaining 'Parties' pages to the cache model  …
* Add new cache model to WarehouseIdentification  …
* Apply new Cache model on BorderTranport Controller
* Add new cache model to TransportDetails page  …
* Create new cache model for containers data  …
> CEDS-1344 Create new cache model for Parties section

- app/controllers/declaration/CarrierDetailsPageController.scala
- app/controllers/declaration/SealController.scala
- app/models/declaration/Parties.scala
- app/services/cache/ExportsCacheModelRepository.scala
- test/controllers/declaration/CarrierDetailsPageControllerSpec.scala
- test/controllers/declaration/LocationControllerSpec.scala
- test/controllers/declaration/SealControllerSpec.scala
- test/models/declaration/SupplementaryDeclarationTestData.scala
- test/services/WcoMetadataMapperSpec.scala
- test/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/GoodsLocationBuilderSpec.scala
* Add seal to the new cache model
* Add CarrierDetails to new cache model
* Format code using Scalafmt
> CEDS-1344 Add Seal and CarrierDetails missing data

- app/forms/declaration/RepresentativeDetails.scala
- app/services/cache/mapping/SubmissionMetaDataBuilder.scala
- app/services/cache/mapping/declaration/CancellationRequestBuilder.scala
- app/services/cache/mapping/declaration/DeclarationBuilder.scala
- app/services/mapping/declaration/AgentBuilder.scala
- app/services/mapping/declaration/GoodsItemQuantityBuilder.scala
- app/services/mapping/declaration/TypeCodeBuilder.scala
- test/services/cache/CacheTestData.scala
- test/services/cache/mapping/SubmissionMetaDataBuilderSpec.scala
- test/services/cache/mapping/declaration/CancellationRequestBuilderSpec.scala
- test/services/cache/mapping/declaration/DeclarationBuilderSpec.scala
This is for the 1st part of the new caching. Old cache mapping is intact.
> CEDS-1411: Started mapping to wco-dec from new exportsCacheModel

- app/metrics/ExportsMetrics.scala
- test/controllers/CancelDeclarationControllerSpec.scala
- test/services/SubmissionServiceSpec.scala
Hide fields and change test to more integration fashion.
This would allow create stub/mocks easier.
> Hermetization in ExportMetrics

- app/services/mapping/declaration/DeclarationBuilder.scala
- app/services/mapping/goodsshipment/AEOMutualRecognitionPartiesBuilder.scala
- app/services/mapping/goodsshipment/ConsigneeBuilder.scala
- app/services/mapping/goodsshipment/DestinationBuilder.scala
- app/services/mapping/goodsshipment/ExportCountryBuilder.scala
- app/services/mapping/goodsshipment/GoodsShipmentBuilder.scala
- app/services/mapping/goodsshipment/GoodsShipmentNatureOfTransactionBuilder.scala
- app/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala
- app/services/mapping/goodsshipment/UCRBuilder.scala
- app/services/mapping/goodsshipment/WarehouseBuilder.scala
- test/services/mapping/XmlMarshallingSpec.scala
- test/services/mapping/declaration/DeclarationBuilderSpec.scala
- test/services/mapping/goodsshipment/AEOMutualRecognitionPartiesBuilderSpec.scala
- test/services/mapping/goodsshipment/ConsigneeBuilderSpec.scala
- test/services/mapping/goodsshipment/DestinationBuilderSpec.scala
- test/services/mapping/goodsshipment/ExportCountryBuilderSpec.scala
- test/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala
- test/services/mapping/goodsshipment/NatureOfTransactionBuilderSpec.scala
- test/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala
- test/services/mapping/goodsshipment/UCRBuilderSpec.scala
- test/services/mapping/goodsshipment/WarehouseBuilderSpec.scala
...for package services.mapping.goodsshipment
> Removed ref to CacheMap from builders and fixed unit tests

- app/services/mapping/declaration/DeclarationBuilder.scala
- app/services/mapping/declaration/consignment/DeclarationConsignmentBuilder.scala
- app/services/mapping/goodsshipment/consignment/ArrivalTransportMeansBuilder.scala
- app/services/mapping/goodsshipment/consignment/ConsignmentBuilder.scala
- app/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilder.scala
- app/services/mapping/goodsshipment/consignment/ContainerCodeBuilder.scala
- app/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilder.scala
- app/services/mapping/goodsshipment/consignment/GoodsLocationBuilder.scala
- app/services/mapping/goodsshipment/consignment/TransportEquipmentBuilder.scala
- test/services/mapping/declaration/consignment/DeclarationConsignmentBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ArrivalTransportMeansBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ConsignmentCarrierBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/ContainerCodeBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/GoodsLocationBuilderSpec.scala
- test/services/mapping/goodsshipment/consignment/TransportEquipmentBuilderSpec.scala
in services.mapping.goodsshipment.consignment
> CEDS-1470 - remove CacheMap from builders 

- app/controllers/declaration/AdditionalDeclarationTypeController.scala
- app/controllers/declaration/CarrierDetailsController.scala
- app/controllers/declaration/ConsigneeDetailsController.scala
- app/controllers/declaration/ConsignmentReferencesController.scala
- app/controllers/declaration/DeclarantDetailsController.scala
- app/controllers/declaration/DeclarationAdditionalActorsController.scala
- app/controllers/declaration/DeclarationHolderController.scala
- app/controllers/declaration/DispatchLocationController.scala
- app/controllers/declaration/ExporterDetailsController.scala
- app/controllers/declaration/RepresentativeDetailsController.scala
- test/controllers/declaration/ConsignmentReferencesControllerSpec.scala
- test/controllers/declaration/DeclarantDetailsControllerSpec.scala
- test/controllers/declaration/DeclarationAdditionalActorsControllerSpec.scala
- test/controllers/declaration/DeclarationHolderControllerSpec.scala
- test/controllers/declaration/DispatchLocationControllerSpec.scala
- test/controllers/declaration/ExporterDetailsControllerSpec.scala
- test/controllers/declaration/RepresentativeDetailsControllerSpec.scala
- test/unit/controllers/declaration/AdditionalDeclarationTypeControllerSpec.scala
- test/unit/controllers/declaration/CarrierDetailsControllerSpec.scala
- test/unit/controllers/declaration/ConsigneeDetailsControllerSpec.scala
DispatchLocationController
AdditionalDeclarationTypeController
ConsignmentReferencesController
ExporterDetailsController
DeclarantDetailsController
RepresentativeDetailsController
ConsigneeDetailsController
CarrierDetailsController
DeclarationAdditionalActorsController
DeclarationHolderController
> CEDS-1474: removed old caching from controllers and updated tests.

- app/controllers/actions/JourneyAction.scala
- app/controllers/declaration/SealController.scala
- app/controllers/declaration/WarehouseIdentificationController.scala
- test/base/MockCustomsCacheService.scala
- test/base/MockExportsCacheService.scala
- test/controllers/declaration/WarehouseIdentificationControllerSpec.scala
- test/forms/declaration/WarehouseIdentificationSpec.scala
- test/integration/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemIntegrationTest.scala
- test/services/cache/ExportsCacheModelBuilder.scala
- test/services/cache/ExportsItemBuilder.scala
- test/services/mapping/governmentagencygoodsitem/AdditionalInformationBuilderSpec.scala
- test/services/mapping/governmentagencygoodsitem/GovernmentAgencyGoodsItemBuilderSpec.scala
- test/services/mapping/governmentagencygoodsitem/GovernmentProcedureBuilderSpec.scala
- test/services/mapping/governmentagencygoodsitem/PackagingBuilderSpec.scala
- test/services/mapping/governmentagencygoodsitem/StatisticalValueAmountBuilderSpec.scala
- test/unit/base/ControllerSpec.scala
- test/unit/controllers/CancelDeclarationControllerSpec.scala
- test/unit/controllers/ChoiceControllerSpec.scala
- test/unit/controllers/declaration/AdditionalFiscalReferencesControllerSpec.scala
- test/unit/controllers/declaration/AdditionalInformationControllerSpec.scala
- test/unit/controllers/declaration/BorderTransportControllerSpec.scala
- test/unit/controllers/declaration/PackageInformationControllerSpec.scala
- test/unit/controllers/declaration/SealControllerSpec.scala
- test/unit/controllers/declaration/WarehouseIdentificationControllerSpec.scala
- test/unit/mock/ErrorHandlerMocks.scala
- test/unit/mock/ExportsMetricsMocks.scala
- test/unit/mock/JourneyActionMocks.scala
- test/views/declaration/WarehouseIdentificationViewSpec.scala
Include setup to reset mocks after each test case.
> Ceds 1249 warehouse identification

- app/connectors/CustomsDeclareExportsConnector.scala
- app/connectors/exchange/ExportsDeclarationExchange.scala
- app/controllers/ChoiceController.scala
- app/models/ExportsDeclaration.scala
- test/base/MockConnectors.scala
- test/base/TestHelper.scala
- test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala
- test/connectors/CustomsDeclareExportsConnectorSpec.scala
- test/connectors/exchange/ExportsDeclarationExchangeSpec.scala
- test/models/declaration/SupplementaryDeclarationTestData.scala
- test/services/cache/ExportsDeclarationBuilder.scala
- test/services/cache/ExportsDeclarationRepositorySpec.scala
- test/views/declaration/spec/ViewSpec.scala
This removes draftId as it wasnt used & adds connector methods for the new back end endpoints
> CEDS-1479 Create Find Connector Methods

- app/controllers/actions/AuthAction.scala
- test/base/CustomExportsBaseSpec.scala
- test/base/MetricsMocks.scala
- test/base/MockAuthAction.scala
- test/controllers/CancelDeclarationControllerSpec.scala
- test/models/PageTest.scala
- test/models/PaginatedTest.scala
- test/services/SubmissionServiceSpec.scala
- test/unit/tools/Stubs.scala
Plus extract as field retrieve paramters
> CEDS-1501 Add authorisation time metric

- app/controllers/declaration/AdditionalDeclarationTypeController.scala
- app/controllers/navigation/Navigator.scala
- test/base/MockNavigator.scala
- test/controllers/navigation/NavigatorTest.scala
- test/unit/controllers/declaration/AdditionalDeclarationTypeControllerSpec.scala
This will hopefully speed up adding Save & Continue to each page as we don't have to have the `FormAction.bind` logic in each controller, the navigator can handle that
> CEDS-1511 Pull Out Action logic into Navigator

- app/assets/stylesheets/customsdecexfrontend-app.scss
- app/views/saved_declarations.scala.html
- app/views/submissions.scala.html
…afts and submitted declarations
> CEDS-1511 - make table headers bold (to match prototype) 

- docs/Customs Declare Exports Auth AutoComplete.js
- docs/Customs Declare Exports AutoComplete.js
Allow tempermonkey engine to update script if it change
> CEDS-1553 Use UpdateURL and version in quick submit script

- app/controllers/CancelDeclarationController.scala
- app/forms/CancelDeclaration.scala
- app/forms/Lrn.scala
- app/forms/declaration/ConsignmentReferences.scala
- app/models/ExportsDeclaration.scala
- app/views/declaration/summary/summary_page.scala.html
- conf/messages.en
- test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala
- test/connectors/exchange/ExportsDeclarationExchangeSpec.scala
- test/forms/declaration/ConsignmentReferencesSpec.scala
- test/services/audit/AuditServiceSpec.scala
- test/services/cache/ExportsDeclarationBuilder.scala
- test/unit/controllers/CancelDeclarationControllerSpec.scala
- test/unit/controllers/declaration/ConsignmentReferencesControllerSpec.scala
- test/views/RemoveSavedDeclarationsViewSpec.scala
- test/views/SavedDeclarationsViewSpec.scala
- test/views/cancellation/CancelDeclarationViewSpec.scala
- test/views/declaration/ConsignmentReferencesViewSpec.scala
We send UCR instead of LNR in cancelation request.
> CEDS-1699 Use LRN on cancelation declaration

- app/views/components/table_row_no_change_link.scala.html
- app/views/declaration/summary/parties_section.scala.html
- test/views/declaration/summary/PartiesSectionViewSpec.scala
- test/views/declaration/summary/SummaryPageViewSpec.scala
> CEDS-1669 - remove declarant address from summary page

- app/controllers/declaration/SummaryController.scala
- app/models/requests/JourneyRequest.scala
- app/services/SubmissionService.scala
- project/AppDependencies.scala
- test/services/SubmissionServiceSpec.scala
- test/unit/controllers/declaration/SummaryControllerSpec.scala
- Remove WCO library as its no longer used
- Remove Request from service layer
> CEDS-1673 Remove unnecessary PUT

- app/views/rejected_notification_errors.scala.html
Added `thead` and `tbody` tags after discussion with design.
> CEDS-1802 Change order of columns on rejected notification page

- app/controllers/CancelDeclarationController.scala
- app/services/SubmissionService.scala
- app/services/audit/AuditService.scala
- test/services/SubmissionServiceSpec.scala
- test/services/audit/AuditServiceSpec.scala
This was the feedback from TxM team.
> CEDS-1675 Change the case of TXM ids to camelcase

- app/assets/javascripts/autocomplete.js
- app/assets/stylesheets/partials/_autocomplete.scss
- app/assets/stylesheets/partials/_utilities.scss
Behaves same as other inputs plus have same width and height.
> CEDS-1635 Unify length of input field for autocomplete

- app/views/components/buttons/add_button.scala.html
- app/views/components/fields/field_multiple_values.scala.html
- app/views/components/fields/field_text_multiple_values.scala.html
- app/views/declaration/item_type.scala.html
- test/views/declaration/ItemTypeViewSpec.scala
Form needs to specify whether it needs an "Add" or "AddField" button
Added unique id to add button to make the form compliant and testing easier
> CEDS-1094 add button bug

- app/services/audit/AuditService.scala
- test/services/audit/AuditServiceSpec.scala
This is a request from Titi from the TxM team. The opinion is that TxM
wants to standardise the payloads format.
> CEDS-1675 Lower case the audit transactionName value

- app/controllers/declaration/InlandTransportDetailsController.scala
- app/controllers/declaration/SupervisingCustomsOfficeController.scala
- app/controllers/navigation/Navigator.scala
- app/views/declaration/departure_transport.scala.html
- app/views/declaration/inland_transport_details.scala.html
- conf/declaration.routes
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/unit/controllers/declaration/InlandTransportDetailsControllerSpec.scala
- test/unit/controllers/declaration/SupervisingCustomsOfficeControllerSpec.scala
- test/views/declaration/BorderTransportViewSpec.scala
- test/views/declaration/DepartureTransportViewSpec.scala
- test/views/declaration/InlandTransportDetailsViewSpec.scala
Renamed Warehouse Details to Inland Transport Details in routes, Controller, view and tests.
> CEDS-1954  New 'Inland mode of transport' page

- docs/Customs Declare Exports AutoComplete.js
As part of the GDS Design system the styling has changed and broke the
quick submit button on the choice page.
> CEDS-1976 Fix Quick Submit button

- docs/Customs Declare Exports AutoComplete.js
- small improvements to qs script
> * Updated *

- app/connectors/exchange/ExportsDeclarationExchange.scala
- app/controllers/declaration/BorderTransportController.scala
- app/controllers/declaration/DepartureTransportController.scala
- app/controllers/declaration/SealController.scala
- app/controllers/declaration/TransportPaymentController.scala
- app/models/ExportsDeclaration.scala
- app/models/declaration/Transport.scala
- app/views/declaration/summary/transport_section.scala.html
- test/connectors/exchange/ExportsDeclarationExchangeSpec.scala
- test/models/declaration/ExportDeclarationTestData.scala
- test/services/cache/ExportsDeclarationBuilder.scala
Waits for https://github.com/hmrc/customs-declare-exports/pull/140 - after those version1 of reads could be removed.
> CEDS-2036 Use transport field for border,departure and containers

- app/controllers/declaration/FiscalInformationController.scala
- app/views/declaration/summary/countries_section.scala.html
- app/views/declaration/summary/transaction_section.scala.html
- app/views/declaration/summary/transport_section.scala.html
- app/views/declaration/summary/warehouse_section.scala.html
- test/views/declaration/summary/CountriesSectionViewSpec.scala
- test/views/declaration/summary/TransactionSectionViewSpec.scala
- test/views/declaration/summary/TransportSectionViewSpec.scala
- test/views/declaration/summary/WarehouseSectionViewSpec.scala
Additionally Improvements around Fiscal Information Controller in separate commit
> CEDS-2048 Summary page for Occasional Declaration

- app/views/declaration/summary/countries_section.scala.html
- app/views/declaration/summary/item_section.scala.html
- app/views/declaration/summary/locations_section.scala.html
- app/views/declaration/summary/parties_section.scala.html
- app/views/declaration/summary/transaction_section.scala.html
- app/views/declaration/summary/transport_section.scala.html
- test/views/declaration/summary/CountriesSectionViewSpec.scala
- test/views/declaration/summary/ItemSectionViewSpec.scala
- test/views/declaration/summary/LocationsSectionViewSpec.scala
- test/views/declaration/summary/PartiesSectionViewSpec.scala
- test/views/declaration/summary/TransactionSectionViewSpec.scala
- test/views/declaration/summary/TransportSectionViewSpec.scala
Removed section according to prototype.
> CEDS-2049 Update summary page for clearance request

- app/controllers/declaration/TransportLeavingTheBorderController.scala
- app/views/declaration/summary/locations_section.scala.html
- test/unit/controllers/declaration/TransportLeavingTheBorderControllerSpec.scala
- test/views/declaration/summary/LocationsSectionViewSpec.scala
Fix navigation problem around adding containers.
> CEDS-2049 Enable express consignment option on summary page

- app/assets/stylesheets/partials/_base.scss
- app/views/components/table_row.scala.html
- app/views/declaration/summary/additional_and_authorised_parties_section.scala.html
- app/views/declaration/summary/containers.scala.html
- app/views/declaration/summary/package_information.scala.html
- app/views/declaration/summary/related_documents.scala.html
- app/views/declaration/summary/supporting_documents.scala.html
- app/views/declaration/summary/union_and_national_codes.scala.html
* All lists and tables of questions/answers should be the same width,
and the Change link should be right-aligned
* All Questions should be vertically-aligned top
* Headings and sub-heading should not be wrapped.
* The vertical spacing between elements of the submission form at the
bottom of the screen should be consistent with the prototype.
This is to align the page to match the prototype.
This page is not accessible, this will be addressed once we move to the
GDS design system
with @apodi @alsahid1993
> CEDS-2097 Align tables and change links

- app/views/declaration/summary/countries_section.scala.html
- app/views/declaration/summary/item_section.scala.html
- test/views/declaration/summary/CountriesSectionViewSpec.scala
This is to make the `Change` link more accessible for visually impaired
users.
> CEDS-2097 Add 'Change' to the visually hidden link

- app/forms/declaration/DeclarantDetails.scala
- app/forms/declaration/DeclarationAdditionalActors.scala
- app/forms/declaration/DeclarationHolder.scala
- app/forms/declaration/EntityDetails.scala
- app/utils/validators/forms/FieldValidator.scala
- conf/messages.en
- test/forms/declaration/DeclarationAdditionalActorsSpec.scala
- test/forms/declaration/EntityDetailsSpec.scala
- test/unit/controllers/declaration/CarrierDetailsControllerSpec.scala
- test/unit/controllers/declaration/ConsigneeDetailsControllerSpec.scala
- test/unit/controllers/declaration/DeclarantDetailsControllerSpec.scala
- test/unit/controllers/declaration/DeclarationAdditionalActorsControllerSpec.scala
- test/unit/controllers/declaration/DeclarationHolderControllerSpec.scala
- test/unit/controllers/declaration/ExporterDetailsControllerSpec.scala
- test/unit/controllers/declaration/RepresentativeDetailsControllerSpec.scala
- test/unit/forms/declaration/ExporterDetailsSpec.scala
- test/views/declaration/CarrierDetailsViewSpec.scala
- test/views/declaration/ConsigneeDetailsViewSpec.scala
- test/views/declaration/DeclarantDetailsViewSpec.scala
- test/views/declaration/DeclarationAdditionalActorsViewSpec.scala
- test/views/declaration/DeclarationHolderViewSpec.scala
- test/views/declaration/ExporterDetailsViewSpec.scala
- test/views/declaration/RepresentativeDetailsViewSpec.scala
CEDS-1098: EORI validation for GB at start and max and min length
* EORI must start with GB or gb
* EORI must be min 14 characters
* EORI must be max 17 characters
* Only digits are allowed after GB
> CEDS-1098: EORI validation for GB at start and max and min length

- app/assets/stylesheets/partials/_base.scss
- app/views/declaration/summary/containers.scala.html
- app/views/declaration/summary/related_documents.scala.html
- app/views/declaration/summary/supporting_documents.scala.html
- app/views/declaration/summary/union_and_national_codes.scala.html
An example of this being needed is when we add a high number of seals to a
container.
> CEDS-2097 Add Vertical Align and Word-break to left most value

- app/forms/declaration/DeclarantDetails.scala
- app/forms/declaration/DeclarationAdditionalActors.scala
- app/forms/declaration/DeclarationHolder.scala
- app/forms/declaration/EntityDetails.scala
- app/utils/validators/forms/FieldValidator.scala
- conf/messages.en
- test/views/declaration/CarrierDetailsViewSpec.scala
- test/views/declaration/ConsigneeDetailsViewSpec.scala
- test/views/declaration/ExporterDetailsViewSpec.scala
* Removed validation for only GB. 
* First 2 entries must be letters.
* Max limit of 17 & minimum limit of 3.
> CEDS-1098: Non GB EORI number allowed

- app/forms/declaration/DeclarantDetails.scala
- test/forms/declaration/DeclarantDetailsSpec.scala
Was validating empty and valid format at the same time
> CEDS-2122 - Two validation errors for declarant

- app/forms/declaration/CommodityMeasure.scala
- app/utils/validators/forms/FieldValidator.scala
- test/unit/forms/declaration/CommodityMeasureSpec.scala
- test/utils/validators/forms/FieldValidatorSpec.scala
* Allow user to enter zero after decimal e.g 31.0 or 31.00
* Unit test cases
> Regression issue fixed

- app/forms/declaration/GoodsLocation.scala
- test/views/declaration/LocationViewSpec.scala
- test/views/declaration/summary/LocationsSectionViewSpec.scala
CEDS-1757: Fix for right order of error messages for city and post code
> CEDS-1757: Fix for right order of error messages for city and post code

- docs/Customs Declare Exports AutoComplete.js
- updated DUCR generation it should be 8GB + 12 digits after
> * Quick Submit *

- app/controllers/navigation/Navigator.scala
> Updated Back link navigation

- app/connectors/exchange/ExportsDeclarationExchange.scala
- app/controllers/declaration/ItemsSummaryController.scala
- app/models/ExportsDeclaration.scala
- test/connectors/exchange/ExportsDeclarationExchangeSpec.scala
- test/models/declaration/ExportDeclarationTestData.scala
- test/services/cache/ExportsDeclarationBuilder.scala
Changing the collection type from Set to Seq ensures that insertion order is maintained
> CEDS-1439 - maintain item ordering

- app/forms/declaration/CommodityDetails.scala
- test/forms/declaration/CommodityDetailsSpec.scala
Commodity Code consists of 8 digits exactly
> CEDS-1961 - Updated Validation for Export Commodity Code

- app/controllers/declaration/OfficeOfExitController.scala
- app/controllers/navigation/Navigator.scala
- test/unit/controllers/declaration/OfficeOfExitControllerSpec.scala
- test/views/declaration/TotalPackageQuantityViewSpec.scala
Add tests for office-of-exit for other declaration types
> CEDS-2033 Skip total-item-information for clearance request

- app/controllers/declaration/OfficeOfExitController.scala
- app/controllers/declaration/TotalNumberOfItemsController.scala
- app/controllers/declaration/TotalPackageQuantityController.scala
- app/controllers/navigation/Navigator.scala
- test/unit/controllers/declaration/OfficeOfExitControllerSpec.scala
- test/unit/controllers/declaration/TotalNumberOfItemsControllerSpec.scala
- test/unit/controllers/declaration/TotalPackageQuantityControllerSpec.scala
CEDS-2188 - Skip 6/18 'Total number of packages' from Clearance Requests
> CEDS-2195 - Skip 8/5 'Nature of Transaction' for Clearance Requests

- app/controllers/declaration/InlandTransportDetailsController.scala
- app/controllers/declaration/TransportLeavingTheBorderController.scala
- app/controllers/navigation/Navigator.scala
- test/unit/controllers/declaration/InlandTransportDetailsControllerSpec.scala
- test/unit/controllers/declaration/TransportLeavingTheBorderControllerSpec.scala
- test/views/declaration/DepartureTransportViewSpec.scala
the border' for Clearance Requests
> CEDS-2196 - Skip '7/14 Identity of active means of transport crossing

- app/controllers/declaration/DeclarationHolderController.scala
- app/controllers/declaration/OriginationCountryController.scala
- app/controllers/navigation/Navigator.scala
- test/unit/controllers/declaration/OriginationCountryControllerSpec.scala
- test/views/declaration/LocationViewSpec.scala
For Clearance Requests, data element '5/14 Country of Dispatch' is not required in any circumstances.
> CEDS-2194 - Skip 5/14 Country of Dispatch for C21

- app/views/declaration/destinationCountries/country_of_routing.scala.html
- app/views/declaration/total_package_quantity.scala.html
- app/views/declaration/transport_container_summary.scala.html
- conf/messages.en
- test/views/declaration/TotalPackageQuantityViewSpec.scala
- test/views/declaration/destinationCountries/RoutingCountryQuestionViewSpec.scala
* Country of Routing Codes
* Total Package Quantity
> CEDS-1771 Add tariff link for two new pages

- app/controllers/declaration/NactCodeController.scala
- app/controllers/declaration/StatisticalValueController.scala
- app/controllers/navigation/Navigator.scala
- app/models/declaration/ExportItem.scala
- test/unit/controllers/declaration/NactCodeControllerSpec.scala
- test/unit/controllers/declaration/StatisticalValueControllerSpec.scala
For Clearance Requests, the '8/6 Statistical Value' data element is not required in any circumstances.
> CEDS-2222 - Skip '8/6 Statistical Value' for Clearance Requests

- app/views/BackButton.scala
- app/views/choice_page.scala.html
- app/views/components/gds/gdsMainTemplate.scala.html
- app/views/declaration_information.scala.html
Quick PR to bring the creation of back-link in line with movements services
> BAU - create BackButton model for use with GDS template

- app/forms/declaration/TotalNumberOfItems.scala
- app/views/declaration/total_number_of_items.scala.html
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/views/declaration/TotalNumberOfItemsViewSpec.scala
First page for CEDS-2228 - Move Section 4 of the Standard Declaration journey to GDS
> CEDS-2228 - total_number_of_items page to GDS (invoice and exchange rate)

- app/views/components/details_content_link.scala.html
- app/views/components/gds/detailsContentLink.scala.html
- app/views/components/gds/exportsInputTextArea.scala.html
- app/views/components/gds/paragraphBody.scala.html
- app/views/components/gds/saveAsDraft.scala.html
- app/views/declaration/commodity_details.scala.html
- app/views/declaration/cus_code.scala.html
- app/views/declaration/fiscal_information.scala.html
- app/views/declaration/nature_of_transaction.scala.html
- app/views/declaration/un_dangerous_goods_code.scala.html
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/views/ChoiceViewSpec.scala
- test/views/declaration/CommodityDetailsViewSpec.scala
- test/views/declaration/ConsignmentReferencesViewSpec.scala
- test/views/declaration/CusCodeViewSpec.scala
- test/views/declaration/DeclarationChoiceViewSpec.scala
- test/views/declaration/DispatchLocationViewSpec.scala
- test/views/declaration/FiscalInformationViewSpec.scala
- test/views/declaration/LocationViewSpec.scala
- test/views/declaration/NatureOfTransactionViewSpec.scala
- test/views/declaration/RepresentativeDetailsViewSpec.scala
- test/views/declaration/TotalNumberOfItemsViewSpec.scala
- test/views/declaration/UNDangerousGoodsCodeViewSpec.scala
- test/views/declaration/additionaldeclarationtype/DeclarationTypeViewSpec.scala
- test/views/declaration/commodityMeasure/CommodityMeasureViewSpec.scala
- test/views/declaration/spec/ViewMatchers.scala
Pages covered
- What was the nature of the transaction?
- Onward Supply Relief (Y/N page only)
- Commodity Details
- Does the item have a UN Dangerous Goods Code?
- Do these goods have a CUS code?
> CEDS-2228 - Move Section 4 of the Standard Declaration journey to GDS

- app/views/declaration/goods_location.scala.html
- app/views/declaration/representative_details.scala.html
- test/views/declaration/LocationViewSpec.scala
Updated representative_details.scala.html - Page contains only one h1 element
Updated goods_location.scala.html - title elements
Jira ticket: https://jira.tools.tax.service.gov.uk/browse/CEDS-2226
> CEDS-2226 Updated Heading & Elements

- conf/declaration.routes
https://jira.tools.tax.service.gov.uk/browse/CEDS-2277
Point 3 is only required to be addressed within this PR:
The URL for this page has changed from /warehouse-identification to /warehouse-details
CEDS-2229 covers the other points:
> CEDS-2277 Updated URL

- docs/Customs Declare Exports AutoComplete.js
- update version to 1.34
- additional actors url updated
- package information updated to XD (as Khurram mentioned one day)
- warehouse url updated
- submit button updated
- supplementary SDP is rejected on QA - seems like it is a data problem, rest works fine
> * BAU - Quick Submit *

- app/views/declaration/consignee_details.scala.html
- test/views/declaration/ConsigneeDetailsViewSpec.scala
Change header back to 'Parties'.
> CEDS-2236 Improve Consignee Details Page

- app/views/components/gds/changeButton.scala.html
- app/views/components/gds/exportsInputText.scala.html
- app/views/declaration/seal_add.scala.html
- app/views/declaration/seal_remove.scala.html
- app/views/declaration/transport_container_add.scala.html
- app/views/declaration/transport_container_add_first.scala.html
- app/views/declaration/transport_container_remove.scala.html
- app/views/declaration/transport_container_summary.scala.html
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/views/declaration/SealAddViewSpec.scala
- test/views/declaration/TransportContainerAddFirstViewSpec.scala
- test/views/declaration/TransportContainerAddViewSpec.scala
- test/views/declaration/TransportContainerRemoveViewSpec.scala
- test/views/declaration/TransportContainerSummaryViewSpec.scala
- change add seal page to single question title format
> CEDS-2344 - change transport container pages to GDS

- docs/Customs Declare Exports AutoComplete.js
> BAU - Quick Submit

- app/assets/stylesheets/partials/_gdsBase.scss
- app/views/components/gds/addButton.scala.html
- app/views/components/gds/removeButton.scala.html
- app/views/declaration/declaration_additional_actors.scala.html
- app/views/declaration/items_summary.scala.html
- conf/messages.en
- test/views/declaration/DeclarationAdditionalActorsViewSpec.scala
- test/views/declaration/ItemSummaryViewSpec.scala
* Fix Additional Actors messages
* GDSify Items Summary page
**NOTE:** **Depends on https://github.com/hmrc/cds-exports-acceptance/pull/410** _(Smoke tests are green)_
> CEDS-2358 GDSify Items Summary page

- app/views/declaration/supervising_customs_office.scala.html
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/views/declaration/SupervisingCustomsOfficeViewSpec.scala
**Depends on** https://github.com/hmrc/cds-exports-acceptance/pull/418
_(Smoke tests are passing locally)_
> CEDS-2346 Convert page layout to GDS Design System

- .gitignore
- app/forms/declaration/CarrierDetails.scala
- app/forms/declaration/EntityDetails.scala
- app/views/declaration/carrier_details.scala.html
- app/views/declaration/consignee_details.scala.html
- app/views/declaration/declarant_details.scala.html
- app/views/declaration/declaration_additional_actors.scala.html
- app/views/declaration/declaration_holder.scala.html
- app/views/declaration/exporter_details.scala.html
- app/views/declaration/representative_details.scala.html
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/views/declaration/CarrierDetailsViewSpec.scala
- test/views/declaration/ConsigneeDetailsViewSpec.scala
- test/views/declaration/DeclarantDetailsViewSpec.scala
- test/views/declaration/DeclarationAdditionalActorsViewSpec.scala
- test/views/declaration/DeclarationHolderViewSpec.scala
- test/views/declaration/RepresentativeDetailsViewSpec.scala
- test/views/declaration/summary/SummaryMessagesSpec.scala
* Add validation on mapping with 
* BAU - Ignore floobits files
* Rename parties header message key 
with @bambuchaAdm 
**NOTE:** **Depends on** https://github.com/hmrc/cds-exports-acceptance/pull/419
_UAT tests are green_
> CEDS-2069 Allow either EORI or Address details

- app/views/declaration/summary/parties_section.scala.html
- docs/Customs Declare Exports AutoComplete.js
- test/views/declaration/summary/PartiesSectionViewSpec.scala
Also fix Quick Submit - representation status required always now.
> CEDS-2401 - remove representative EORI from summary if not asked

- app/controllers/declaration/AdditionalInformationRequiredController.scala
- app/controllers/declaration/CommodityMeasureController.scala
- app/views/declaration/additional_information.scala.html
- app/views/declaration/additional_information_required.html
- app/views/declaration/additional_information_required.scala.html
- conf/declaration.routes
- conf/messages.en
- test/unit/controllers/declaration/CommodityMeasureControllerSpec.scala
- test/views/declaration/AdditionalInformationRequiredViewSpec.scala
- test/views/declaration/AdditionalInformationViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CEDS-2383
> CEDS - 2383 Split the additional information page into the two pages	

- app/forms/declaration/GoodsLocationForm.scala
- app/forms/declaration/additionaldocuments/DocumentsProduced.scala
- test/forms/declaration/DocumentsProducedSpec.scala
- test/forms/declaration/GoodsLocationFormSpec.scala
Covers two pages missed off CEDS-1881 ticket in declarations service
> CEDS-1881 - allow lowercase entry for goods location and document status/type

- app/models/declaration/ExportItem.scala
- app/views/declaration/destinationCountries/routing_country_question.scala.html
- test/services/cache/ExportItemSpec.scala
Package information mandatory on clearance journey unless procedure code is 0019
> CEDS-2378 - Package Information validation fix for clearance journey

- app/views/declaration/summary/accepted_declaration_page.scala.html
- app/views/declaration/summary/item_section.scala.html
This ensures that the main sections of each item are not broken between
pages.
> CEDS-2509 Avoid breaking the page for multiple items

- app/views/declaration/documentsProduced/documents_produced.scala.html
- app/views/declaration/documentsProduced/documents_produced_add.scala.html
- app/views/declaration/documentsProduced/documents_produced_change.scala.html
- app/views/declaration/documentsProduced/documents_produced_edit_content.scala.html
- app/views/declaration/documentsProduced/documents_produced_remove.scala.html
- test/views/declaration/DocumentsProducedAddViewSpec.scala
- test/views/declaration/DocumentsProducedChangeViewSpec.scala
- test/views/declaration/DocumentsProducedRemoveViewSpec.scala
- test/views/declaration/DocumentsProducedViewSpec.scala
> CEDS-2486 - fixes for remove documents produced page

- app/assets/stylesheets/partials/_gdsBase.scss
- app/views/components/gds/gdsMainTemplate.scala.html
> CEDS-2528 - keyboard navigation fix - make back-link first element

- app/assets/stylesheets/partials/_gdsBase.scss
- app/views/declaration/border_transport.scala.html
- app/views/declaration/departure_transport.scala.html
- app/views/declaration/warehouse_identification.scala.html
- So that they work better with 200% font size
- Removed redundant css for previous auto-complete fix
> CEDS-2529 - updated some input field widths

- app/services/ead/EADService.scala
- app/views/components/gds/exportsDateInput.scala.html
- app/views/declaration/goods_location.scala.html
- app/views/declaration/supervising_customs_office.scala.html
- test/views/declaration/DocumentsProducedAddViewSpec.scala
- test/views/declaration/DocumentsProducedChangeViewSpec.scala
Tests are on Jenkins so I'm not able to verify if those fixes will solve issues from accessibility tests
> CEDS-2527 Some accessibility fixes

- app/views/components/fields/field_accessible_autocomplete_with_header.scala.html
- app/views/declaration/destinationCountries/change_routing_country.scala.html
- app/views/declaration/destinationCountries/destination_country.scala.html
- app/views/declaration/exporter_details.scala.html
- test/views/declaration/destinationCountries/ChangeRoutingCountryViewSpec.scala
Fixes for a couple of instances where labels with no content were being rendered.
> BAU - empty label fixes

- app/config/AppConfig.scala
- app/controllers/actions/AuthAction.scala
- conf/application.conf
- test/base/MockAuthAction.scala
- test/unit/controllers/actions/EoriAllowListProviderTest.scala
- test/unit/controllers/actions/EoriAllowListTest.scala
Change all occurrences of 'whitelist' to 'allow list'
> CEDS-2674 Replace 'whitelist' and 'blacklist' across services

- app/controllers/declaration/AdditionalFiscalReferencesAddController.scala
- app/controllers/declaration/DeclarationHolderController.scala
- app/controllers/declaration/FiscalInformationController.scala
- app/forms/Mapping.scala
- app/forms/declaration/AdditionalFiscalReference.scala
- app/forms/declaration/RoutingQuestionYesNo.scala
- app/forms/declaration/countries/Countries.scala
- app/test/controllers/FeatureSwitchController.scala
- app/views/components/gds/ActionItemBuilder.scala
- build.sbt
- project/TestPhases.scala
- project/build.properties
- project/plugins.sbt
- test/unit/controllers/declaration/AdditionalFiscalReferencesRemoveControllerSpec.scala
- test/unit/controllers/declaration/DeclarationHolderControllerSpec.scala
- test/unit/tools/Stubs.scala
- test/views/declaration/DeclarationHolderChangeViewSpec.scala
- test/views/declaration/fiscalInformation/AdditionalFiscalReferencesViewSpec.scala
This version seems to be the last reliable version.
Higher versions contain some issues with importing a project. That would
need additional steps and workarounds to make it work.
> CEDS-2659 Upgrade SBT to 1.3.6

- app/controllers/declaration/NactCodeAddController.scala
- app/controllers/declaration/SealController.scala
- app/controllers/declaration/TaricCodeAddController.scala
- app/controllers/declaration/TransportContainerController.scala
- app/controllers/util/MultipleItemsHelper.scala
Update duplication errors to include red indentation and error message for pages with single fields.
> CEDS-2722 Update duplication errors for single field pages

- app/controllers/declaration/AdditionalActorsAddController.scala
- app/controllers/declaration/AdditionalFiscalReferencesAddController.scala
- app/controllers/declaration/AdditionalInformationAddController.scala
- app/controllers/declaration/DeclarationHolderAddController.scala
- app/controllers/declaration/DocumentsProducedAddController.scala
- app/controllers/declaration/PackageInformationAddController.scala
- app/controllers/declaration/PreviousDocumentsController.scala
- app/views/declaration/additionalActors/additional_actors_add.scala.html
- app/views/declaration/additionalInformtion/additional_information_edit_content.scala.html
- app/views/declaration/declarationHolder/declaration_holder_edit_content.scala.html
- app/views/declaration/documentsProduced/documents_produced_edit_content.scala.html
- app/views/declaration/exporter_details.scala.html
- app/views/declaration/fiscalInformation/additional_fiscal_references_add.scala.html
- app/views/declaration/package_information_add.scala.html
- app/views/declaration/previousDocuments/previous_documents_edit.scala.html
Add error indentation for duplication errors to the following pages:
- Additional Actors
- Additional Information
- Additional Fiscal References
- Declaration Holder
- Documents Produces
- Previous Documents
- Package Information
> CEDS-2768 Update duplication errors for multiple field pages

- app/views/declaration/declarationitems/items_add_item.scala.html
- test/views/declaration/declarationitems/ItemsAddItemViewSpec.scala
Work done:
- removed fieldset
- update page
- updated test
> CEDS-2811 Remove unnecessary fieldset from add declaration item page

- app/forms/declaration/additionaldocuments/DocumentWriteOff.scala
Remove duplicated error message for quantity on /items/additional-documentation
> CEDS-2760 Duplicated error message for quantity

- app/config/AppConfig.scala
- app/views/components/exit_survey.scala.html
- app/views/components/feedback_frontend.scala.html
- app/views/declaration/submission_confirmation_page.scala.html
- app/views/user_signed_out.scala.html
- conf/application.conf
- conf/messages.en
- test/config/AppConfigSpec.scala
- test/views/declaration/SubmissionConfirmationPageViewSpec.scala
Add link to Exit Survey on /customs-declare-exports/declaration/confirmation page and on the user log out page.
> CEDS-2889 Set up the Exit Survey for Declaration Service

- README.md
- conf/code-lists/document-type-autocomplete-list.json
- conf/code-lists/location-autocomplete-canonical-list.json
- tariff-codes-parser/src/data/tariff-codes.js
- tariff-codes-parser/src/etl/etl-acceptance.js
- tariff-codes-parser/src/etl/etl-movements.js
- tariff-codes-parser/src/etl/execute-etl.js
- tariff-codes-parser/start.js
Also update Country list for Internal and External Movements
> CEDS-2670 Remove '*' on country names & make hyphens consistent

- app/controllers/SecureMessagingController.scala
- app/views/messaging/partial_wrapper.scala.html
- conf/app.routes
- conf/messages.en
- test/unit/controllers/SecureMessagingControllerSpec.scala
- test/views/messaging/PartialWrapperSpec.scala
Create screen to view individual message and submit a reply.
Include back button and link to declaration dashboard.
> CEDS-3058 View individual message & Reply Success

- app/views/messaging/partial_wrapper.scala.html
Use map on back button implementation on partial wrapper.
> CEDS-3058-fix Fix reply result error for messaging inbox

- app/config/AppConfig.scala
- app/controllers/declaration/NactCodeAddController.scala
- app/views/declaration/nact_code_add_first.scala.html
- conf/application.conf
- conf/messages.en
- test/config/AppConfigSpec.scala
- test/unit/controllers/declaration/NactCodeAddControllerSpec.scala
- test/views/declaration/NactCodeAddFirstViewSpec.scala
Add a new tariff guide link specific for the actual commodity code
the user will have already entered on the previous page.
> [CEDS-3138] National Additional Code

- conf/application.conf
- conf/messages.en
Also set local secureMessagingInbox fetaure flag to be 'exports'
in line with what smoke tests expect.
> [CEDS-3138] Fix missing quote marks

- app/config/AppConfig.scala
- app/views/components/goodsLocationExpander.scala.html
- app/views/declaration/goods_location.scala.html
- conf/application.conf
- conf/messages.en
- test/config/AppConfigSpec.scala
- test/views/declaration/LocationViewSpec.scala
Change title and content on page
Create a new expander that assists users in
finding the correct location codes.
> [CEDS-2886] Goods Location Code page changes

- app/forms/declaration/TransportPayment.scala
- app/views/declaration/summary/transport_section.scala.html
- app/views/declaration/transport_payment.scala.html
- conf/messages.en
- test/controllers/declaration/TransportPaymentControllerSpec.scala
- test/forms/declaration/TransportPaymentSpec.scala
- test/views/declaration/TransportPaymentViewSpec.scala
- test/views/declaration/summary/TransportSectionViewSpec.scala
Making the express transport payment screen mandatory and
adding a new radio option of 'Payment information is
not available'
> [CEDS-3182] New transport payment option

- app/config/AppConfig.scala
- app/connectors/CodeListConnector.scala
- app/models/codes/CommonCode.scala
- app/models/codes/ProcedureCode.scala
- app/utils/JsonFile.scala
- conf/application.conf
- conf/code-lists/procedureCodes.json
- conf/code-lists/procedureCodesC21.json
- test/config/AppConfigSpec.scala
- test/connectors/CodeListConnectorSpec.scala
- test/resources/code-lists/malformedCodes.json
- test/resources/code-lists/manyCodes.json
- test/resources/code-lists/oneCode.json
- test/tools/Stubs.scala
- test/utils/JsonFileSpec.scala
- test/views/declaration/DeclarationChoiceViewSpec.scala
Added new json file containing the code and
descriptions in each supported language.
Plus new connector class to 'pull' code lists
for required locale.
Also make missing config values fail fast
> [CEDS-3225]_Add_json_procedure_code_data_file

- app/forms/declaration/TransportPayment.scala
- app/views/declaration/transport_payment.scala.html
- conf/messages.en
Remove hint text
Default to first radio option from validation error
Modify text for Other option radio
> [CEDS-3128] Fix ticket omissions

- app/config/AppConfig.scala
- app/connectors/CodeListConnector.scala
- app/controllers/declaration/AdditionalProcedureCodesController.scala
- app/services/ProcedureCodeService.scala
- app/services/view/AutoCompleteItem.scala
- app/views/components/fields/field_accessible_autocomplete_with_header.scala.html
- app/views/components/inputs/input_accessible_autocomplete.scala.html
- app/views/declaration/procedureCodes/additional_procedure_codes.scala.html
- conf/application.conf
- conf/code-lists/additionalProcedureCodes.json
- conf/code-lists/linkProcedureCodeToAdditionalProcedureCodes.json
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/config/AppConfigSpec.scala
- test/connectors/CodeListConnectorSpec.scala
- test/controllers/declaration/AdditionalProcedureCodesControllerSpec.scala
- test/services/ProcedureCodeServiceSpec.scala
- test/services/model/AutoCompleteItemSpec.scala
- test/views/declaration/procedureCodes/AdditionalProcedureCodesViewSpec.scala
Swap free text enty of Additional Procedure Code to a drop-down
selection box of only valid codes. Plus content changes
> [CEDS-3198] Additional Procedure Codes page development

- app/forms/declaration/ModeOfTransportCode.scala
- app/views/declaration/transport_leaving_the_border.scala.html
- conf/messages.en
- test/controllers/declaration/TransportLeavingTheBorderControllerSpec.scala
- test/views/declaration/DocumentsProducedAddViewSpec.scala
- test/views/declaration/DocumentsProducedChangeViewSpec.scala
- test/views/declaration/TransportLeavingTheBorderViewSpec.scala
Adding new radio option of RoRo
> [CEDS-3217] Content update for transport leaving the border

- app/controllers/declaration/AdditionalProcedureCodesController.scala
- app/controllers/declaration/ItemsSummaryController.scala
- app/controllers/declaration/ModelCacheable.scala
- app/controllers/declaration/SupervisingCustomsOfficeController.scala
- app/controllers/declaration/TransportLeavingTheBorderController.scala
- app/controllers/declaration/WarehouseIdentificationController.scala
- app/controllers/navigation/Navigator.scala
- app/controllers/util/SupervisingCustomsOfficeHelper.scala
- app/models/ExportsDeclaration.scala
- conf/declaration.routes
- conf/messages.en
- docs/Customs Declare Exports AutoComplete.js
- test/base/MockExportCacheService.scala
- test/controllers/declaration/AdditionalProcedureCodesControllerSpec.scala
- test/controllers/declaration/ItemsSummaryControllerSpec.scala
- test/controllers/declaration/TransportLeavingTheBorderControllerSpec.scala
- test/controllers/declaration/WarehouseIdentificationControllerSpec.scala
- test/views/declaration/ExpressConsignmentViewSpec.scala
- test/views/declaration/InlandTransportDetailsViewSpec.scala
Skip page at /supervising-customs-office if all declaration's items have '1040' as Procedure code and '000' as unique APC
> CEDS-3246 Conditionally skip page at /supervising-customs-office

- app/controllers/declaration/CommodityDetailsController.scala
- app/controllers/declaration/UNDangerousGoodsCodeController.scala
- app/controllers/navigation/Navigator.scala
- app/forms/declaration/CommodityDetails.scala
- app/models/ExportsDeclaration.scala
- test/controllers/declaration/CommodityDetailsControllerSpec.scala
- test/controllers/declaration/UNDangerousGoodsCodeControllerSpec.scala
- test/models/ExportsDeclarationSpec.scala
- test/views/declaration/TaricCodeAddFirstViewSpec.scala
- test/views/declaration/TaricCodesViewSpec.scala
Only show user the cus code page if commodityCode
starts with the chemical prefix digits, else skip
to taric page.
> [CEDS-3301] Skipping CUS code page

- app/controllers/declaration/ConsigneeDetailsController.scala
- app/controllers/declaration/EntryIntoDeclarantsRecordsController.scala
- app/controllers/navigation/Navigator.scala
- test/base/JourneyTypeTestRunner.scala
- test/controllers/declaration/ConsigneeDetailsControllerSpec.scala
- test/controllers/declaration/EntryIntoDeclarantsRecordsControllerSpec.scala
- test/views/declaration/AuthorisationProcedureCodeChoiceViewSpec.scala
Make C21 journeys where user selects EIDR as true visit
the new authorisation-choice page.
> [CEDS-3241] Consignee details navigation update

- app/controllers/declaration/AdditionalActorsController.scala
- app/controllers/declaration/AuthorisationProcedureCodeChoiceController.scala
- app/controllers/declaration/DeclarationHolderRequiredController.scala
- app/controllers/navigation/Navigator.scala
- test/controllers/declaration/AdditionalActorsSummaryControllerSpec.scala
- test/controllers/declaration/AuthorisationProcedureCodeChoiceControllerSpec.scala
- test/views/declaration/DeclarationHolderAddViewSpec.scala
- test/views/declaration/DeclarationHolderRequiredViewSpec.scala
Route other-parties-involved page for occasional
journey types to skip authorisation-choice page.
> [CEDS-3240] Occasional journey navigation update

- app/views/helpers/TimelineEvents.scala
- test/views/DeclarationDetailsViewSpec.scala
Fix an issue with the logic setting buttons on the Timeline as primary or as secondary.
> CEDS-3272 Fix a logic issue

- app/views/declaration_details.scala.html
- conf/messages.en
- test/views/DeclarationDetailsViewSpec.scala
Add a new expander to the Timeline page providing info on DMSCTL notifications
> CEDS-3367 Add a new expander to the Timeline page

- app/controllers/declaration/ConsignmentReferencesController.scala
- app/controllers/navigation/Navigator.scala
- test/controllers/declaration/ConsignmentReferencesControllerSpec.scala
- test/views/declaration/DeclarantExporterViewSpec.scala
On consignment-references page, skip MUCR pages if the
journey type is SUPPLEMENTARY
> [CEDS-3269] Supplementary Skip link to MUCR pages

- app/controllers/declaration/DeclarationHolderAddController.scala
- conf/messages.en
- test/controllers/declaration/DeclarationHolderAddControllerSpec.scala
Validation to stop allowing CSE and EXRR together.
> [CEDS-3374] Make CSE and EXRR values mutually exclusive

- app/config/AppConfig.scala
- app/connectors/CustomsDeclareExportsConnector.scala
- app/controllers/declaration/ConsignmentReferencesController.scala
- app/forms/LrnValidator.scala
- app/forms/declaration/ConsignmentReferences.scala
- app/models/declaration/submissions/Action.scala
- conf/application.conf
- conf/messages.en
- test/config/AppConfigSpec.scala
- test/connectors/CustomsDeclareExportsConnectorIntegrationISpec.scala
- test/controllers/declaration/ConsignmentReferencesControllerSpec.scala
- test/forms/LrnValidatorSpec.scala
- test/forms/declaration/ConsignmentReferencesSpec.scala
The new validation checks whether the same LRN
has not been used in the past 48 hours.
> CEDS-3410 LRN validation on ConsignmentReferences page

- app/views/declaration/summary/amend_summary_page.scala.html
- app/views/declaration/summary/draft_summary_page.scala.html
- conf/messages.en
- test/views/declaration/summary/SummaryPageViewAmmendSpec.scala
- test/views/declaration/summary/SummaryPageViewDraftSpec.scala
- test/views/declaration/summary/SummaryPageViewNormalSpec.scala
- test/views/declaration/summary/SummaryPageViewSpec.scala
Adding warning text and changing 'Continue' button to
be a link.
Also refactoring summary page tests to have one per
'mode'.
> [CEDS-3402] New_content_at_base_of_CYA_page

- app/forms/declaration/TotalNumberOfItems.scala
- conf/messages.en
- test/forms/declaration/TotalNumberOfItemsSpec.scala
Allow commas and periods in numerical values and limit
total number of digits and decimal places for each
field.
> [CEDS-3478] Validation update to total-numbers-of-items

- app/controllers/declaration/ConsignmentReferencesController.scala
- app/utils/validators/forms/FieldValidator.scala
- test/controllers/declaration/ConsignmentReferencesControllerSpec.scala
- test/forms/DucrSpec.scala
- test/forms/declaration/ConsignmentReferencesSpec.scala
- test/utils/validators/forms/FieldValidatorSpec.scala
- test/views/declaration/CarrierEoriNumberViewSpec.scala
...on page at `/consignment-references`
> CEDS-3432 Allow users to enter DUCRs with lowercase letters

- app/controllers/declaration/InlandTransportDetailsController.scala
- app/controllers/navigation/Navigator.scala
- app/views/declaration/inland_transport_details.scala.html
- conf/messages.en
- test/controllers/declaration/BorderTransportControllerSpec.scala
- test/controllers/declaration/InlandTransportDetailsControllerSpec.scala
- test/views/declaration/InlandTransportDetailsViewSpec.scala
Also clean up legacy code still present for invalid journey types.
> [CEDS-3215] Content update and skip conditionality for inland-transport-details

- app/controllers/declaration/InlandTransportDetailsController.scala
- app/controllers/navigation/Navigator.scala
- app/models/ExportsDeclaration.scala
- test/controllers/declaration/InlandTransportDetailsControllerSpec.scala
Page flow was taking user to express_consignment page on supplementary
journeys when this page is not valid for that journey type.
> [CEDS-3215]_Fix_journey_flow_for_supplementary_journeys

- app/controllers/declaration/AdditionalDocumentsController.scala
- app/controllers/declaration/RoutingCountriesSummaryController.scala
- app/controllers/navigation/Navigator.scala
- test/controllers/declaration/AdditionalDocumentsControllerSpec.scala
Fix navigation from the Error page when the declaration has no additional-documents.
> CEDS-3417 Fix navigation from the Error page

- app/controllers/RejectedNotificationsController.scala
- app/controllers/SubmissionsController.scala
- app/views/helpers/NotificationErrorHelper.scala
- app/views/rejected_notification_errors.scala.html
- conf/application.conf
- conf/code-lists/dmsErrorCodes-customised.json
- conf/messages.en
- test/controllers/RejectedNotificationsControllerSpec.scala
- test/views/RejectedNotificationErrorsViewSpec.scala
- test/views/helpers/NotificationErrorHelperSpec.scala
Create new customised error descriptions and titles to be
displayed on error page (plus new content for that page).
> [CEDS-3530] Update content on rejected-notifications page

- app/views/components/gds/exportsInputText.scala.html
- app/views/components/gds/pageTitle.scala.html
- app/views/declaration/mucr_code.scala.html
- app/views/declaration/nact_code_add.scala.html
- app/views/declaration/person_presenting_goods_details.scala.html
- app/views/declaration/representative_details_entity.scala.html
- app/views/declaration/seal_add.scala.html
- app/views/declaration/taric_code_add.scala.html
- app/views/declaration/total_package_quantity.scala.html
- app/views/declaration/transport_container_add.scala.html
- app/views/declaration/warehouse_identification.scala.html
- app/views/helpers/InputTextHelper.scala
Removed the ability of a Label to contain a heading (as they are two
distinctly different things)
> [CEDS-3510] Rewrite headings with labels so they are semantically correct

- app/connectors/CustomsDeclareExportsConnector.scala
- app/views/helpers/NotificationErrorHelper.scala
- test/views/helpers/NotificationErrorHelperSpec.scala
Redact the fieldName and description details from consecutive repeating errors
> [CEDS-3550] Logic for displaying title only or title + description on errors

- app/views/components/inputs/input_accessible_autocomplete.scala.html
- app/views/components/inputs/input_accessible_location_autocomplete.scala.html
Changing the loading of the javascript files to use the
Assets controller routes rather than absolute refs.
> [CEDS-3459] Adding versioned assets call for js files

- app/controllers/declaration/AdditionalInformationController.scala
- app/controllers/declaration/AdditionalInformationRequiredController.scala
- app/controllers/declaration/SupplementaryUnitsController.scala
- app/controllers/navigation/Navigator.scala
- app/services/TariffApiService.scala
- app/views/declaration/additionalInformation/additional_information.scala.html
- app/views/declaration/additionalInformation/additional_information_required.scala.html
- app/views/helpers/NotificationErrorHelper.scala
- docs/Customs Declare Exports AutoComplete.js
- test/controllers/declaration/AdditionalInformationControllerSpec.scala
- test/controllers/declaration/AdditionalInformationRequiredControllerSpec.scala
- test/controllers/declaration/SupplementaryUnitsControllerSpec.scala
- test/controllers/navigation/NavigatorSpec.scala
- test/services/TariffApiServiceSpec.scala
- test/views/declaration/AdditionalInformationRequiredViewSpec.scala
- test/views/declaration/AdditionalInformationViewSpec.scala
- test/views/declaration/ExpressConsignmentViewSpec.scala
- Additional logic for page at '/supplementary-units'
- Backward navigation from Additional-Information section
> CEDS-3369 Additional logic for page at '/supplementary-units'

- app/config/AppConfig.scala
- app/connectors/CodeLinkConnector.scala
- app/views/components/fields/field_accessible_location_autocomplete_with_header.scala.html
- app/views/components/gds/group_address.scala.html
- app/views/components/inputs/input_accessible_location_autocomplete.scala.html
- app/views/declaration/border_transport.scala.html
- app/views/declaration/destinationCountries/change_routing_country.scala.html
- app/views/declaration/destinationCountries/country_of_routing.scala.html
- app/views/declaration/destinationCountries/destination_country.scala.html
- app/views/declaration/destinationCountries/routing_countries_summary.scala.html
- app/views/declaration/summary/countries_section.scala.html
- app/views/helpers/CountryHelper.scala
- conf/application.conf
- conf/code-lists/linkCountryCodeToShortName.json
- test/config/AppConfigSpec.scala
- test/connectors/CodeLinkConnectorSpec.scala
- test/views/declaration/summary/CountriesSectionViewSpec.scala
- test/views/helpers/CountryHelperSpec.scala
Display abbreviated country names (if defined) for the
routing country summary and check your answers pages.
> [CEDS-3566] Create new short names for certain countries

- conf/messages.en
New error messages for handling CSE and EXRR authorisation combination errors.
> [CEDS-3556] Update of validation error on Authorisations page

- app/forms/common/Address.scala
- app/forms/declaration/EntityDetails.scala
- app/utils/validators/forms/FieldValidator.scala
- test/forms/common/AddressSpec.scala
- test/views/declaration/summary/SubmittedDeclarationPageViewSpec.scala
- test/views/declaration/summary/SummaryPageViewSpec.scala
Specifically only allowed in these address fields:
- name
- address
- town
> CEDS-3634 Allow ampersand in all address fields

- app/connectors/TariffApiConnector.scala
- app/controllers/declaration/TaricCodeAddController.scala
- app/services/TariffApiService.scala
- app/views/declaration/additionalDocuments/additional_document_edit.scala.html
- app/views/declaration/additionalDocuments/additional_documents_required.scala.html
- app/views/declaration/commodityMeasure/supplementary_units_yes_no.scala.html
- app/views/declaration/is_licence_required.scala.html
- app/views/declaration/taric_code_add_first.scala.html
- app/views/helpers/CommodityCodeHelper.scala
- test/connectors/TariffApiConnectorISpec.scala
- test/controllers/declaration/TaricCodeAddControllerSpec.scala
- test/services/TariffApiServiceSpec.scala
- test/views/declaration/AdditionalDocumentEditViewSpec.scala
- test/views/declaration/AdditionalDocumentsRequiredViewSpec.scala
- test/views/declaration/TaricCodeAddFirstViewSpec.scala
- test/views/declaration/commodityMeasure/SupplementaryUnitsYesNoViewSpec.scala
… in addition to 10-digits Commodity codes
> CEDS-3698 Commodity-code logic amendment in order to also accept 8-digits codes

- app/models/ExportsDeclaration.scala
- app/views/helpers/DepartureTransportHelper.scala
- test/views/declaration/DepartureTransportViewSpec.scala
Add further condition for appearance of paragraph on whether user selected Road on /inland-transport-details
> CEDS-3773 Make body text conditional and amend test

- app/views/declaration/authorisation_procedure_code_choice.scala.html
Also added the missing redline error message wrap to the radios and question
> CEDS-3571 Make error link skip to first radio

- app/controllers/declaration/AdditionalDocumentAddController.scala
- app/controllers/declaration/AdditionalDocumentChangeController.scala
- app/controllers/declaration/AdditionalDocumentRemoveController.scala
- app/controllers/declaration/AdditionalDocumentsController.scala
- app/controllers/declaration/IsLicenceRequiredController.scala
- app/models/ExportsDeclaration.scala
- test/controllers/declaration/IsLicenceRequiredControllerSpec.scala
Darryl's work on CEDS-3804 and some other fixes to pass regression tests when 999L flag is enabled.
> CEDS-3804 including fixes to pass regression tests

- conf/messages.en
Include the words 'in pounds' in the title.
> CEDS-3583 Update title of statistical-value page

- app/controllers/navigation/Navigator.scala
- test/controllers/navigation/NavigatorSpec.scala
Correct behaviour of "Save and continue" button when in ErrorFix mode
> CEDS-4061 Amend errorfix handling method in navigator

- app/controllers/declaration/AdditionalActorsSummaryController.scala
- app/controllers/declaration/AdditionalDocumentsController.scala
- app/controllers/declaration/AdditionalFiscalReferencesController.scala
- app/controllers/declaration/AdditionalInformationController.scala
- app/controllers/declaration/AdditionalInformationRequiredController.scala
- app/controllers/declaration/DeclarationHolderSummaryController.scala
- app/controllers/declaration/IsLicenceRequiredController.scala
- app/controllers/declaration/ItemsSummaryController.scala
- app/controllers/declaration/PackageInformationSummaryController.scala
- app/controllers/declaration/PreviousDocumentsSummaryController.scala
- app/controllers/declaration/RoutingCountriesController.scala
- app/controllers/declaration/SealController.scala
- app/controllers/declaration/TransportContainerController.scala
- app/controllers/navigation/Navigator.scala
- test/base/MockNavigator.scala
- test/controllers/declaration/EntryIntoDeclarantsRecordsControllerSpec.scala
- test/controllers/declaration/ItemsSummaryControllerSpec.scala
- test/controllers/declaration/PersonPresentingGoodsDetailsControllerSpec.scala
- test/controllers/declaration/TransportContainerControllerSpec.scala
- test/controllers/navigation/NavigatorSpec.scala
- test/views/declaration/summary/sections/ItemSectionViewSpec.scala
The actual changes to meet the ticket requirements are just in `Navigator.handleErrorFixMode`. All other changes are mostly just cosmetic changes.
> CEDS-4062 No Error-Box on 'Additional Documents' page clicking the 'change' link on the page showing the error

- app/views/choice_page.scala.html
- conf/messages.en
- test/base/ExportsTestData.scala
- test/views/ChoiceViewSpec.scala
Reorder radio elements and change text description of last one
> CEDS-4158_Change_order_of_buttons_and_text_on_Choice_page

- app/models/declaration/Parties.scala
- test/forms/declaration/PartiesSpec.scala
Adding it to missing calling block of Parties createDiff method
> CEDS-4765 Authorisation Holders is not included in diff

- conf/messages
- test/views/UnauthorisedEoriViewSpec.scala
Temporary content change while TDR is blocked
> BAU Alter Unauth EORI message in TDR

- app/views/declaration/summary/additional_documents.scala.html
- app/views/declaration/summary/package_information.scala.html
- app/views/declaration/summary/sections/item_section.scala.html
- app/views/declaration/summary/union_and_national_codes.scala.html
- conf/application.conf
- test/views/declaration/declarationitems/ItemsRemoveItemViewSpec.scala
- test/views/declaration/summary/AdditionalDocumentsViewSpec.scala
- test/views/declaration/summary/PackageInformationViewSpec.scala
- test/views/declaration/summary/SubmittedDeclarationPageViewSpec.scala
- test/views/declaration/summary/SummaryPageViewSpec.scala
- test/views/declaration/summary/UnionAndNationalCodesViewSpec.scala
- test/views/declaration/summary/sections/ItemSectionViewSpec.scala
- test/views/declaration/summary/sections/ItemsSectionViewSpec.scala
Reverts hmrc/customs-declare-exports-frontend#1810
> Revert "CEDS-4778 Make all html class or id sequencing linked to index of ele…"

- app/controllers/declaration/ItemsSummaryController.scala
- app/controllers/declaration/RemoveItemsSummaryController.scala
- app/views/components/gds/cancel.scala.html
- app/views/declaration/declarationitems/items_cannot_remove.scala.html
- app/views/declaration/declarationitems/items_remove_item.scala.html
- app/views/declaration/declarationitems/items_summary.scala.html
- app/views/declaration/summary/sections/item_section.scala.html
- conf/declaration.routes
- conf/messages
- test/controllers/declaration/ItemsSummaryControllerSpec.scala
- test/controllers/declaration/RemoveItemsSummaryControllerSpec.scala
- test/services/cache/SubmissionBuilder.scala
- test/views/declaration/declarationitems/ItemsCannotRemoveItemViewSpec.scala
- test/views/declaration/declarationitems/ItemsRemoveItemViewSpec.scala
- test/views/declaration/declarationitems/ItemsSummaryViewSpec.scala
- test/views/declaration/summary/sections/ItemSectionViewSpec.scala
Includes creation of `RemoveItemsSummaryController` to reduce burden on `ItemsSummaryController`
> Ceds 4840 remove item content for existing items

- app/models/declaration/notifications/NotificationError.scala
Adding description field to NotificationError entity
> CEDS-5025 Parse and store Description element from error notifications

- conf/application.conf
- project/plugins.sbt
Reverts hmrc/customs-declare-exports-frontend#1894
CSP breaking some js and styleing on site
> Revert "CEDS-5089 GA4 Update the Content Security Policy"

- app/connectors/CustomsDeclareExportsConnector.scala
- app/controllers/CopyDeclarationController.scala
- app/controllers/SubmissionsController.scala
- app/controllers/declaration/AdditionalProcedureCodesController.scala
- app/controllers/declaration/DeclarationChoiceController.scala
- app/controllers/declaration/ItemsSummaryController.scala
- app/controllers/declaration/ModelCacheable.scala
- app/controllers/declaration/RemoveItemsSummaryController.scala
- app/controllers/declaration/SubmissionController.scala
- app/controllers/declaration/TransportContainerController.scala
- app/controllers/declaration/amendments/AmendDeclarationController.scala
- app/services/AuditCreateDraftDec.scala
- app/services/audit/AuditService.scala
- app/services/cache/ExportsCacheService.scala
- conf/application.conf
- project/plugins.sbt
- test/base/MockConnectors.scala
- test/base/MockExportCacheService.scala
- test/connectors/CustomsDeclareExportsConnectorISpec.scala
- test/controllers/SubmissionsControllerSpec.scala
- test/controllers/declaration/DeclarationChoiceControllerSpec.scala
- test/controllers/declaration/SubmissionControllerSpec.scala
- test/controllers/declaration/amendments/AmendDeclarationControllerSpec.scala
When a new draft dec is created and the new draft has a DUCR value, then create a new audit event to track the milestone.
> CEDS-5205 Add new event on draft dec creation

- app/views/helpers/PointerRecord.scala
- test/views/helpers/PointerRecordSpec.scala
Add readable value method for all country fields
> CEDS-5775 Add consignor details address pointers to PointerRecord

- app/controllers/actions/JourneyAction.scala
Just an attempt to gather more information on what controller/endpoint the problem originates from.
> CEDS-5952 Improve logging for 'JourneyAction' on failed retrieval of a declaration

- app/views/section6/send_by_roro.scala.html
- conf/messages
- conf/messages.cy
- test/views/section6/SendByRoroViewSpec.scala
Reverts hmrc/customs-declare-exports-frontend#2154
> Revert "CEDS-5962: update content Remove CHIEF from 'declaration/send-by-roro…"

- app/views/journey/standard_or_other_journey.scala.html
- app/views/section1/not_declarant.scala.html
- app/views/section2/declarant_exporter.scala.html
- app/views/section2/entry_into_declarants_records.scala.html
- app/views/section3/destination_country.scala.html
- app/views/section4/previousDocuments/previous_documents_summary.scala.html
- app/views/section5/items/items_summary.scala.html
- app/views/section6/transport_leaving_the_border.scala.html
- app/views/summary/sections/section_summary.scala.html
- conf/messages
- conf/messages.cy
- test/views/helpers/CommonMessages.scala
- test/views/journey/StandardOrOtherJourneyViewSpec.scala
- test/views/section2/DeclarantExporterViewSpec.scala
- test/views/summary/sections/SectionSummaryViewSpec.scala
Changes for the [CEDS-6119](https://jira.tools.tax.service.gov.uk/browse/CEDS-6119)
> CEDS-6119 Standardise return links in the declaration journey

- app/views/journey/standard_or_other_journey.scala.html
- app/views/section1/not_declarant.scala.html
- app/views/section2/declarant_exporter.scala.html
- app/views/section2/entry_into_declarants_records.scala.html
- app/views/section3/destination_country.scala.html
- app/views/section4/previousDocuments/previous_documents_summary.scala.html
- app/views/section5/items/items_summary.scala.html
- app/views/section6/transport_leaving_the_border.scala.html
- app/views/summary/sections/section_summary.scala.html
- conf/messages
- conf/messages.cy
- test/views/helpers/CommonMessages.scala
- test/views/journey/StandardOrOtherJourneyViewSpec.scala
- test/views/section2/DeclarantExporterViewSpec.scala
- test/views/summary/sections/SectionSummaryViewSpec.scala
Reverts hmrc/customs-declare-exports-frontend#2207
> Revert "CEDS-6119 Standardise return links in the declaration journey"

- app/views/dashboard/DashboardHelper.scala
- conf/messages
- conf/messages.cy
- test/views/dashboard/DashboardViewSpec.scala
Removed hidden text that did not match
> CEDS-6161_Accessible_name_does_not_match_visible_name

- app/views/amendments/amendment_submission.scala.html
- app/views/summary/legal_declaration.scala.html
Remove fieldset from form pages
> CEDS-6177_Fieldset_missing_legend

- app/views/amendments/amendment_submission.scala.html
- app/views/components/gds/exportsInputText.scala.html
- app/views/components/gds/group_address.scala.html
- app/views/section4/invoice_and_exchange_rate.scala.html
- app/views/summary/legal_declaration.scala.html
- test/views/amendments/AmendmentSubmissionViewSpec.scala
- test/views/section2/CarrierDetailsViewSpec.scala
- test/views/section2/ConsigneeDetailsViewSpec.scala
- test/views/section2/ConsignorDetailsViewSpec.scala
- test/views/section2/ExporterDetailsViewSpec.scala
- test/views/section4/InvoiceAndExchangeRateViewSpec.scala
- test/views/summary/LegalDeclarationViewSpec.scala
To:
/declaration/carrier-address
/declaration/consignee-details
/declaration/consignor-address
/declaration/exporter-address
/declaration/invoices-and-exchange-rate
/declaration/submit-your-declaration
/declaration/submit-your-amendment
> CEDS-6180_Missing_autocomplete_attribute_values

- app/views/helpers/TimelineEvents.scala
- conf/messages
- conf/messages.cy
- test/views/helpers/TimelineEventsSpec.scala
Added a visually hidden span to the view details link that specifys the date and time of the event
> CEDS-6176_View_details_links_not_distinguishable
