app/controllers/supplementary/AdditionalInformationController.scala, app/forms/supplementary/AdditionalInformation.scala, app/models/declaration/supplementary/AdditionalInformationData.scala, app/models/declaration/supplementary/SupplementaryDeclarationData.scala, app/views/supplementary/additional_information.scala.html, app/views/supplementary/summary/additional_information_section.scala.html, app/views/supplementary/summary/summary_page.scala.html, conf/messages.en, test/controllers/supplementary/AdditionalInformationControllerSpec.scala, test/controllers/supplementary/SummaryPageControllerSpec.scala, test/forms/supplementary/AdditionalInformationSpec.scala, test/models/declaration/supplementary/SupplementaryDeclarationDataSpec.scala
* User should be able to enter up to 99 entries as per existing
validations for this data element
* User should not be able to enter the same value more than once
* This data element is made up of 2 fields. Both fields must be
populated for user to add the entry
* The entries should be displayed as a list and show that the two
fields are associated. E.g. 'field1-field2'
=> CEDS-949 Add multiplicity to 2/2 AdditionalInformation

app/controllers/supplementary/DocumentsProducedController.scala, app/controllers/supplementary/ProcedureCodesPageController.scala, app/forms/supplementary/DocumentsProduced.scala, app/models/declaration/supplementary/DocumentsProducedData.scala, app/models/declaration/supplementary/SupplementaryDeclarationData.scala, app/views/supplementary/documents_produced.scala.html, app/views/supplementary/summary/additional_documentation_section.scala.html, app/views/supplementary/summary/summary_page.scala.html, conf/messages.en, test/controllers/supplementary/DocumentsProducedControllerSpec.scala, test/forms/supplementary/AdditionalInformationSpec.scala, test/forms/supplementary/DocumentsProducedSpec.scala, test/models/declaration/supplementary/SupplementaryDeclarationDataSpec.scala
* User should be able to enter up to 99 entries as per existing
validations for this data element
* User should not be able to enter the same value more than once
* This data element is made up of 6 fields
* The entries should be displayed as a list and show that the 6
fields are associated
=> CEDS-949 Add multiplicity to 2/3 DocumentsProduced

app/views/supplementary/documents_produced.scala.html, app/views/supplementary/summary/additional_documentation_section.scala.html, test/controllers/supplementary/SummaryPageControllerSpec.scala
* **Display Additional Documentation on a table**
Due to multiplicity we need to display multiple documents and after speaking with @raghu1978 we have agreed that we would use a table format.
In the future we also need to think about ability to change and add documents from the summary page.
* **Replace <th> with <td> for an emtpy table header**
According to guidelines we should not have empty table headers replacing it with `<td>`
=> CEDS-950 Additional Documentation fixes

app/controllers/supplementary/SummaryPageController.scala, app/views/supplementary/summary/summary_page.scala.html, app/views/supplementary/summary/summary_page_no_data.scala.html, conf/messages.en, test/controllers/supplementary/SummaryPageControllerSpec.scala
If the user does not provide information we consider mandatory, they
should not be able to access Summary page. Currently it is LRN only.
=> CEDS-992 Add mandatory info validation before displaying Summary page

app/controllers/supplementary/TransportInformationContainersPageController.scala, app/forms/supplementary/TransportInformation.scala, app/forms/supplementary/TransportInformationContainer.scala, app/models/declaration/supplementary/SupplementaryDeclarationData.scala, app/models/declaration/supplementary/TransportInformationContainerData.scala, app/views/components/add_save_button.scala.html, app/views/components/single_value_elements_table.scala.html, app/views/supplementary/add_transport_containers.scala.html, app/views/supplementary/additional_information.scala.html, app/views/supplementary/declaration_additional_actors.scala.html, app/views/supplementary/documents_produced.scala.html, app/views/supplementary/summary/summary_page.scala.html, app/views/supplementary/summary/transport_containers_section.scala.html, app/views/supplementary/summary/transport_section.scala.html, app/views/supplementary/transport_information.scala.html, conf/messages.en, conf/supplementary.routes, test/controllers/supplementary/ProcedureCodesPageControllerSpec.scala, test/controllers/supplementary/SummaryPageControllerSpec.scala, test/controllers/supplementary/TransportInformationContainersPageControllerSpec.scala, test/controllers/supplementary/TransportInformationPageControllerSpec.scala, test/forms/supplementary/TransportInformationContainerSpec.scala, test/forms/supplementary/TransportInformationSpec.scala, test/models/declaration/supplementary/SupplementaryDeclarationDataSpec.scala
**THIS IS WORK IN PROGRESS. DO NOT MERGE.** 
* **Remove the 'Container ID' input field from the `/transport-information` page**
This removes the text input field from the Transport Information page.
This was requested by @raghu1978. From now on, pages with single and
multiple items will be separated. Multiple items will be asked in a
separate page.
* **Route user to add-transport-containers page**
If the user has selected that he is using any container, then the
next page being presented will the /add-transport-caontainers where
we present the add to list pattern and the user can enter multiple
container ids.
If the user does not have any container to enter then the journey will
proceed to the /total-numbers-of-items page.
* **Provide ability to add multiple containers**
This is loosely …
=> CEDS-976 Add multiple transport containers

app/config/AppConfig.scala, app/connectors/CustomsDeclareExportsConnector.scala, app/controllers/declaration/SummaryPageController.scala, app/services/WcoMetadataJavaMappingStrategy.scala, app/services/WcoMetadataMapper.scala, app/services/WcoMetadataMappingStrategy.scala, app/services/WcoMetadataScalaMappingStrategy.scala, app/services/mapping/MetaDataBuilder.scala, app/services/mapping/declaration/DeclarationBuilder.scala, app/test/controllers/TestingUtilitiesController.scala, conf/application.conf, project/AppDependencies.scala, test/base/CustomExportsBaseSpec.scala, test/config/AppConfigSpec.scala, test/connectors/CustomsDeclareExportsConnectorSpec.scala, test/controllers/declaration/SummaryPageControllerWithScalaMappingSpec.scala, test/resources/wco_dec_metadata.xml, test/services/WcoMetadataJavaMappingStrategySpec.scala, test/services/WcoMetadataScalaMappingStrategySpec.scala, test/services/mapping/MetaDataBuilderSpec.scala, test/services/mapping/XmlMarshallingSpec.scala
* **Add featureFlag to switch between WCO-DEC Mapping strategies**
* **Refactor `submitExportDeclaration` signature**
This is to ensure ease the creation of the WCO-DEC payload a avoid
leaking the logic on how to get the XML String payload into the
`CustomsDeclareExportsConnector.submitExportDeclaration` function.
* **Update wco-dec version to allow serialisation of WCO-DEC Declaration**
* **Map WCO-DEC Metadata based on a Mapping Strategy**
. There is never an elegant way to maintain backwards compatibility in
code, so this is the best attempt at it:
Create a Java and Scala WCO-DEC Mapping classes
. Classes renamed to represent which model (Scala or Java) they are
mapping too. This is better than using "Old" and "New" naming
conventions.
. Having two mappers, for a Scala(old) and …
=> CEDS-1146 Add featureFlag to switch between WCO-DEC Mapping strategies

app/controllers/declaration/SummaryPageController.scala, app/services/WcoMetadataMapper.scala
The error was caused due to a tail recursion, due to the methods having
the same name as the strategy mapping classes.
=> CEDS-1146 Fix Stack Overflow Error

app/config/AppConfig.scala, app/controllers/declaration/SummaryPageController.scala, app/services/WcoMetadataMapper.scala, conf/application.conf, test/base/CustomExportsBaseSpec.scala
This was causing a ClassCastException only picked up when the
application was started, meaning the unit tests failed to pick this
problem.
Instead of using Dependency Injection on the controller we will instead
use the AppConfig to return an instance of the Mapping Strategy (each
one based on the Scala or Java model)
=> CEDS-1146 Stop injecting the WcoMetadataMapper

project/AppDependencies.scala
The previous version of this library cause the leak.
In practice this library is not used in our codebase.
=> CEDS-1140 Fix for the leak

app/forms/common/Address.scala, app/services/mapping/goodsshipment/AEOMutualRecognitionPartiesBuilder.scala, app/services/mapping/goodsshipment/ConsigneeBuilder.scala, app/services/mapping/goodsshipment/ConsignmentBuilder.scala, app/services/mapping/goodsshipment/DestinationBuilder.scala, app/services/mapping/goodsshipment/ExportCountryBuilder.scala, app/services/mapping/goodsshipment/PreviousDocumentsBuilder.scala, app/services/mapping/goodsshipment/TransactionNatureCodeBuilder.scala, app/services/mapping/goodsshipment/UCRBuilder.scala, app/services/mapping/goodsshipment/WarehouseBuilder.scala, test/forms/declaration/DocumentSpec.scala, test/forms/declaration/EntityDetailsSpec.scala, test/forms/declaration/TransportInformationSpec.scala, test/resources/wco_dec_metadata.xml, test/services/mapping/declaration/DeclarationBuilderSpec.scala, test/services/mapping/goodsshipment/AEOMutualRecognitionPartiesBuilderSpec.scala, test/services/mapping/goodsshipment/ConsigneeBuilderSpec.scala, test/services/mapping/goodsshipment/ConsignmentBuilderSpec.scala, test/services/mapping/goodsshipment/DestinationBuilderSpec.scala, test/services/mapping/goodsshipment/ExportCountryBuilderSpec.scala, test/services/mapping/goodsshipment/GoodsShipmentBuilderSpec.scala, test/services/mapping/goodsshipment/PreviousDocumentsBuilderSpec.scala, test/services/mapping/goodsshipment/TransactionTypeBuilderSpec.scala, test/services/mapping/goodsshipment/UCRBuilderSpec.scala, test/services/mapping/goodsshipment/WarehouseBuilderSpec.scala
If empty fields/strings reach the mapping strategy we should not
instantiate new instances as it will cause the WCO-DEC schema to fail
=> CEDS-1146 Fix Empty values on new mapping strategy

app/services/WcoMetadataJavaMappingStrategy.scala, app/services/mapping/declaration/AgentBuilder.scala, app/services/mapping/declaration/BorderTransportMeansBuilder.scala, app/services/mapping/declaration/DeclarantBuilder.scala, app/services/mapping/declaration/ExporterBuilder.scala, test/models/declaration/SupplementaryDeclarationDataSpec.scala, test/resources/wco_dec_metadata.xml, test/services/mapping/declaration/AgentBuilderSpec.scala, test/services/mapping/declaration/DeclarantBuilderSpec.scala, test/services/mapping/declaration/DeclarationBuilderSpec.scala, test/services/mapping/declaration/ExporterBuilderSpec.scala
After a conversation with @raghu1978 we have realised that a lot of the
mapping logic checks are overly defensive as the production code will
never allow data to be in a given state.
For example on a form where a EORI and an address is being requested,
only one or them will be requested and none of them can be
`None/Null/Empty`.
=> CEDS-1143 Check the form validation and align the mapping

app/services/mapping/goodsshipment/DestinationBuilder.scala, conf/application.conf, test/services/mapping/goodsshipment/DestinationBuilderSpec.scala
The fulldec is not supported in the new or old mapping strategy,
simply because we did not do the mapping for destination `ExportCountry`
and `DestinationCountry` (both of them have a supplementary/standard form)
We need to go to the form and check which fields we need to map to.
=> WIP: CEDS-1046 Map standard journey fields

app/controllers/declaration/TransportContainerController.scala, app/views/components/single_value_elements_table.scala.html, app/views/declaration/add_transport_containers.scala.html, app/views/declaration/additional_information.scala.html, app/views/declaration/declaration_holder.scala.html, app/views/declaration/documents_produced.scala.html, app/views/declaration/package_information.scala.html, app/views/declaration/previous_documents.scala.html, app/views/declaration/seal.scala.html, conf/declaration.routes, test/controllers/declaration/DeclarationHolderControllerSpec.scala, test/services/ItemsCachingServiceSpec.scala
Pages that allow entering multiple values and have tables with values
already entered did not handle pressing ENTER key properly. It triggered
the first submit button found on the page, which was 'Remove' button in
most cases.
This commit changes it to trigger 'Add' button instead.
=> CEDS-1203 Change ENTER key to trigger Add button instead of Remove

app/controllers/declaration/DestinationCountriesController.scala, app/controllers/declaration/ItemTypePageController.scala, app/views/declaration/destination_countries_standard.scala.html, app/views/declaration/item_type.scala.html, test/controllers/declaration/DestinationCountriesControllerSpec.scala
When a page contains both single and multi-value fields, there was a
problem that after adding new value the single ones would disappear
after page refresh.
=> CEDS-1093 Retain other fields values when adding new value

app/connectors/CustomsDeclareExportsConnector.scala, app/controllers/ChoiceController.scala, app/controllers/SubmissionsController.scala, app/models/Submission.scala, app/views/submissions.scala.html, conf/app.routes, conf/application.conf, test/base/MockConnectors.scala, test/config/AppConfigSpec.scala, test/connectors/CustomsDeclareExportsConnectorSpec.scala, test/connectors/NrsConnectorSpec.scala, test/controllers/NotificationsControllerSpec.scala, test/controllers/SubmissionsControllerSpec.scala
Now, instead of one call to the backend, there are two, but the logic
around calculating the number of notifications for submission
has been moved to SubmissionController from backend service.
=> CEDS-942 Change submission notifications handling

app/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilder.scala, app/services/mapping/goodsshipment/consignment/TransportEquipmentBuilder.scala, test/resources/wco_dec_metadata.xml, test/services/mapping/goodsshipment/consignment/ConsignmentBuilderSpec.scala, test/services/mapping/goodsshipment/consignment/DepartureTransportMeansBuilderSpec.scala
`DepartureTransportMeans.identificationTypeCode` should be mapped based
on the `BorderTransport` and not on the `TransportDetails`
=> CEDS-1224 Fix DepartureTransportMeans builder

conf/application.conf
The config is to exclude the controller to not to audit the requests on the page.
this is the initial fix  with config, there should be long term fix with customised filer for audit that has been suggested by TXM team if we have more pages with issues when the code list has been introduced
=> [CEDS-1244] - disable audit for destination-countries page

conf/application.conf
At the moment TXM is stating that all of our
`DestinationCountriesController` audit events are exceeding the response
body limit.
This is happening regardless of us setting `needsAuditing` to `false`.
With this change I want to understand if the Audit config is correctly
setup, because once it is deployed to QA it should stop logging the
errors.
If it does not stop logging, than this is a sign that the configuration
is not setup correctly.
=> CEDS-1244 Stop logging TXM implicit audit events

conf/application.conf
Controllers that do require TXM auditing configuration need to be
wrapped in the controllers object.
=> CEDS-1244 Correct the TXM auditing configuration

app/controllers/ChoiceController.scala, app/controllers/declaration/AdditionalDeclarationTypePageController.scala, app/controllers/declaration/ConsignmentReferencesController.scala, app/controllers/declaration/DispatchLocationPageController.scala, app/controllers/declaration/ExporterDetailsPageController.scala, app/controllers/declaration/ItemsSummaryController.scala, app/controllers/declaration/ModelCacheable.scala, app/controllers/declaration/ProcedureCodesPageController.scala, app/services/cache/ExportItem.scala, app/services/cache/ExportsCacheModelRepository.scala, app/services/cache/ExportsCacheService.scala, app/views/declaration/items_summary.scala.html, conf/declaration.routes, test/base/CustomExportsBaseSpec.scala, test/controllers/ChoiceControllerSpec.scala, test/controllers/declaration/AdditionalDeclarationTypePageControllerSpec.scala, test/controllers/declaration/ConsignmentReferencesControllerSpec.scala, test/controllers/declaration/DispatchLocationPageControllerSpec.scala, test/controllers/declaration/ExporterDetailsPageControllerSpec.scala, test/controllers/declaration/ProcedureCodesPageControllerSpec.scala, test/services/cache/ExportsCacheModelRepositorySpec.scala, test/services/cache/ExportsCacheServiceSpec.scala
Added test for cache service and reverted auth code changes
Added cache to submit on initial 5 controllers
=> CEDS-1303: add reactivemongo cache model

app/services/mapping/MetaDataBuilder.scala, test/services/mapping/MetaDataBuilderSpec.scala
It seems that when we submit a declaration cancellation we only setup
the declaration and not the metadata.
=> CEDS-1420 Pass correct functionCode/typeCode

app/controllers/declaration/ProcedureCodesPageController.scala, test/controllers/declaration/ProcedureCodesPageControllerSpec.scala
If we had a list of additional procedure codes, but the form was empty
we would get a pattern matching error.
We should ensure the current form has the `procedureCode` sent on the
reuqest payload.
=> CEDS-1410 Fix ProcedureCode form validation

app/utils/validators/forms/FieldValidator.scala
One of most time consuming in regexp is pattern compilation. `String.match()` recompiles pattern on each call. This should lead to performance benefits and reduce memory consumption.
=> Avoid pattern recompilation

app/controllers/declaration/AdditionalInformationController.scala, app/controllers/declaration/DocumentsProducedController.scala, app/controllers/declaration/PackageInformationController.scala, app/controllers/declaration/ProcedureCodesController.scala, app/services/cache/ExportsCacheService.scala, test/base/CustomExportsBaseSpec.scala, test/base/MockExportCacheService.scala, test/services/SubmissionServiceSpec.scala
I expect as part of Save & Resume that this service will be converted to use the back end rather than Mongo.
This PR preps the service a little by removing some methods that wont be available via the backend
=> CEDS-1511 Remove deprecated cache service method

app/forms/declaration/Document.scala, app/views/declaration/previous_documents.scala.html, test/unit/controllers/SubmissionsControllerSpec.scala, test/unit/controllers/declaration/SummaryControllerSpec.scala, test/views/declaration/ConsignmentReferencesViewSpec.scala, test/views/declaration/PreviousDocumentsViewSpec.scala
This was a request from @leszeklorek so that the CI tests can search
the html elements by their new name, making the domain language in code,
test and business consistent.
=> CEDS-1475 Rename HTML ids to `Related document`

app/controllers/SavedDeclarationsController.scala, app/views/choice_page.scala.html, conf/messages.en
- order (and text) of choice items changed to reflect latest prototype
- cleared the declarationId from session when landing on the "saved drafts" page so that when you navigate back to the choice page the previously viewed dec type is not pre-selected.
=> CEDS-1487 - fix couple of issues with 'choice' page

app/controllers/declaration/SealController.scala, app/controllers/declaration/TransportDetailsController.scala, app/views/declaration/destination_countries_standard.scala.html, test/unit/controllers/declaration/SealControllerSpec.scala, test/unit/controllers/declaration/TransportDetailsControllerSpec.scala
When in Draft mode, at the end of the journey you would be taken to the `/saved-summary`, similar in Amend mode.
If you click "Save and continue" on the final page of the journey you are now always taken to `/summary` (your mode reverts to Normal)
=> CEDS-1511 Fix Save & Resume Button Location & Summary Page Links

app/controllers/declaration/TransportContainerController.scala, app/controllers/declaration/TransportDetailsController.scala, test/unit/controllers/declaration/TransportContainerControllerSpec.scala, test/unit/controllers/declaration/TransportDetailsControllerSpec.scala
Previously the TransportContainerController and SealController used to set the "Mode" to normal when re-directing to SummaryController.
This was missed during the recent re-factoring of Container/Seals.   The exit point from this mini-journey is when the user selects "No" to "do you want to add another container.
There was also a similar problem when coming from the TransportDetails page having selected "No" to having used containers
=> CEDS-1402 - fix bug when redirecting to summary page

app/config/AppConfig.scala, conf/application.conf, test/config/AppConfigSpec.scala, test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala
As part of the mapping story we had to create a second version of the
endpoints, to consume a JSON payload as opposed to a XML payload,
therefore every single conflicting endpoint ended up being prefixed
by /v2.
This task is to remove this prefix.
=> CEDS-1651 Remove /v2 prefix from REST endpoints

app/forms/declaration/LegalDeclaration.scala, test/forms/declaration/LegalDeclarationSpec.scala
This is to allow a wider set of characters than just English a-zA-Z
characters.
With this change the following name/job patterns will be allowed:
```
Mathias d'Arras
Martin Luther King, Jr.
Hector Sausage-Hausen
```
=> CEDS-1608 Allow a wider range of characters for LegalDeclaration

app/views/components/back_link.scala.html, app/views/declaration/summary/summary_page.scala.html, conf/messages.en, test/views/declaration/summary/SummaryPageViewSpec.scala
- change the url and text for the "Back" button when on summary screen when amending a rejected declaration.
=> CEDS-1676 - Back link for declaration 'error list view'

app/controllers/util/SubmissionDisplayHelper.scala, app/models/declaration/notifications/Notification.scala, app/models/declaration/submissions/Action.scala, app/models/declaration/submissions/SubmissionStatus.scala, app/services/model/RejectionReason.scala, app/views/notifications.scala.html, app/views/submission_notifications.scala.html, app/views/submissions.scala.html, test/base/MockConnectors.scala, test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala, test/controllers/util/SubmissionDisplayHelperSpec.scala, test/models/declaration/notifications/NotificationSpec.scala, test/models/declaration/submissions/SubmissionStatusSpec.scala, test/unit/controllers/NotificationControllerSpec.scala, test/unit/controllers/SubmissionsControllerSpec.scala, test/unit/services/model/RejectionReasonSpec.scala, test/views/NotificationsViewSpec.scala, test/views/SubmissionsViewSpec.scala
This PR requires both of the changes to the BE - i.e. the new `notification.actionId` and `action.id` fields
=> CEDS-1691 - notification field rename

app/models/declaration/submissions/Action.scala, test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala, test/unit/controllers/RejectedNotificationsControllerSpec.scala, test/views/NotificationsViewSpec.scala, test/views/RejectedNotificationErrorsViewSpec.scala
Something Ed suggested when I did the "conversationId" field rename but forgot to push.
=> CEDS-1691 - re-order action fields

app/controllers/CancelDeclarationController.scala, app/controllers/navigation/Navigator.scala, app/services/SubmissionService.scala, app/services/audit/AuditService.scala, test/controllers/navigation/NavigatorTest.scala, test/models/declaration/SupplementaryDeclarationTestData.scala, test/services/SubmissionServiceSpec.scala, test/services/audit/AuditServiceSpec.scala, test/unit/controllers/CancelDeclarationControllerSpec.scala
Delegate the responsibility of converting a Declaration or Cancellation
form to a JsObject to the AuditService.
This makes clear who the responsibility is, although we now need to
create two methods to audit a declaration submission and a cancellation.
=> CEDS-1612 Stop performing Json.toJson outside of Audit method

app/assets/stylesheets/customsdecexfrontend-app.scss
This change puts a yellow border around all button elements when they have focus.  This includes secondary (grey) buttons as well as the "Save and come back later" buttons which are rendered as links.
=> CEDS-1724 Improve focus states on secondary buttons

app/assets/javascripts/autocomplete.js
This is an element that is generated by JS on our pages that require
list codes.
I decided to wrap the `<input>` element with a `<label>` in order to
avoid having to name unique ids, since on some pages we have more than
one autocomplete element.
=> CEDS-1119 Add Label to autocomplete element

app/models/Pointer.scala, test/models/PointerSpec.scala, test/unit/services/model/RejectionReasonSpec.scala
We used to presume a numerical section meant it was a sequence.
This assumption is not correct.
Sequence sections are now rendered in JSON as `#1` (for index 1)
e.g.
Pointer Before: `abc.1.def`
Pointer After: `abc.#1.def`
It means we can convert to and from the string/json version and retain the "section type"
=> CEDS-1695 Fix for Pointer Numerical Field Sections

app/controllers/declaration/TotalNumberOfItemsController.scala, app/views/declaration/previous_documents.scala.html, test/unit/controllers/declaration/DestinationCountriesControllerSpec.scala, test/unit/controllers/declaration/TotalNumberOfItemsControllerSpec.scala, test/views/declaration/PreviousDocumentsViewSpec.scala
A Simplified Declaration requires fewer data elements to be completed
than a Standard Declaration.
This change captures the requirement to skip the 'Nature of Transaction'
page, which is not relevant to Simplified Declaration.
=> CEDS-1853 Skip 'Nature of Transaction' for Simplified Journey

app/connectors/CustomsDeclareExportsConnector.scala, app/models/ExportsDeclaration.scala, app/services/audit/AuditService.scala, test/services/audit/AuditServiceSpec.scala
After the last TxM review, we were asked not to audit the `createDateTime`
and `updateDateTime` in the following MongoDB format:
```
"createdDateTime": {
"$date": 1571135745223
}
```
The approach is to have a serialisation strategy for TxM audit and
another one for MongoDB
=> CEDS-1675 Change format of Audit declation dates

app/controllers/declaration/PackageInformationController.scala, app/views/declaration/additional_information.scala.html, test/unit/controllers/declaration/PackageInformationControllerSpec.scala, test/views/declaration/AdditionalInformationViewSpec.scala
A Simplified Declaration requires fewer data elements to be completed
than a Standard Declaration.
This change captures the requirement to skip the 'commodity-measure'
page, which is not relevant to Simplified Declaration.
=> CEDS-1851 Skip 'Commodity measurements' for Simplified Journey

app/controllers/declaration/ItemsSummaryController.scala, app/models/declaration/ExportItem.scala, test/services/cache/ExportItemSpec.scala, test/unit/controllers/declaration/ItemsSummaryControllerSpec.scala
As part of the Simplified journey, we had to remove the commodity
measurements page from the item journey.
This change implies a change on the Items Summary validation rules for
the journey in question.
=> CEDS-1851 Items summary page allows a Simplified journey item

app/controllers/declaration/OfficeOfExitController.scala, app/controllers/navigation/Navigator.scala, app/forms/DeclarationPage.scala, app/forms/declaration/BorderTransport.scala, app/forms/declaration/Document.scala, app/views/declaration/previous_documents.scala.html, app/views/declaration/summary/items_section.scala.html, app/views/declaration/summary/summary_page.scala.html, test/unit/controllers/declaration/OfficeOfExitControllerSpec.scala, test/views/declaration/PreviousDocumentsViewSpec.scala, test/views/declaration/summary/SummaryPageViewSpec.scala
A Simplified Declaration requires fewer data elements to be completed
than a Standard Declaration.
This change captures the requirement to skip the 'total-numbers-of-items'
page, which is not relevant to Simplified Declaration.
=> CEDS-1843 Skip 'Enter Item Information' Page

app/controllers/declaration/SupervisingCustomsOfficeController.scala, app/controllers/declaration/WarehouseIdentificationController.scala, app/views/declaration/supervising_customs_office.scala.html, app/views/declaration/warehouse_details.scala.html, conf/declaration.routes, conf/messages.en, test/unit/controllers/declaration/SupervisingCustomsOfficeControllerSpec.scala, test/unit/controllers/declaration/WarehouseIdentificationControllerSpec.scala, test/views/declaration/SupervisingCustomsOfficeViewSpec.scala, test/views/declaration/WarehouseDetailsViewSpec.scala, test/views/declaration/WarehouseIdentificationViewSpec.scala
Created new Supervising Customs Office controller and view.
Added endpoint to declaration.routes.
Removed the Supervising Customs Office field from Warehouse Details page.
Changed Back button on Warehouse Details page and 'Save and Continue' button on Warehouse Identification page to direct to Supervising Customs Office page.
Added View Spec and Controller Spec for Supervising Customs Office, and updated Warehouse Identification Controller spec and Warehouse Details View Spec.
=> CEDS-1953 New 'Where is the supervising customs office?' page

app/controllers/declaration/WarehouseDetailsController.scala, test/unit/controllers/declaration/WarehouseDetailsControllerSpec.scala
This is due to trying to maintain the same model, which with hindsight
was a bad idea. After @janeturner completes the screen-splitting we will
come back to clean the model and the cache updates functions.
=> CEDS-1953 Keep the data previously entered when clicking back button

app/controllers/actions/JourneyAction.scala, test/controllers/actions/JourneyActionSpec.scala, test/controllers/actions/TypedJourneyActionTest.scala
Similar functionality to the Movements & Internal UI
Allows us to restrict access to pages e.g.
```
def displayPage(mode: Mode): Action[AnyContent] = (authenticate andThen journeyType(JourneyType.STANDARD)) { implicit request =>
Ok(some_page())
}
```
Or
```
def displayPage(mode: Mode): Action[AnyContent] = (authenticate andThen journeyType(JourneyType.STANDARD, JourneyType.SUPPLEMENTARY)) { implicit request =>
Ok(some_page())
}
```
To restrict to multiple types
=> CEDS Allow JourneyAction to be restricted to Dec Type

app/views/components/fields/removable_elements_table.scala.html, app/views/declaration/additional_information.scala.html, app/views/declaration/declaration_additional_actors.scala.html, app/views/declaration/documents_produced.scala.html, app/views/declaration/items_summary.scala.html, app/views/declaration/package_information.scala.html, app/views/declaration/previous_documents.scala.html, app/views/declaration/transport_container_summary.scala.html, app/views/submissions.scala.html, test/controllers/actions/JourneyActionSpec.scala, test/views/declaration/DeclarationAdditionalActorsViewSpec.scala, test/views/declaration/PackageInformationViewSpec.scala, test/views/declaration/PreviousDocumentsViewSpec.scala
As per https://webaim.org/techniques/tables/data#headers:
The scope attribute tells the browser and screen reader that everything
within a column that is associated to the header with scope="col" in
that column, and that a cell with scope="row" is a header for all
cells in that row.
All <th> elements should generally always have a scope attribute.
=> CEDS-1126 Associate Data Cells with appropriate headers

app/assets/stylesheets/partials/_base.scss
This prevents the table `Change` link from missaligning on the summary
page if long words or long sentences are used.
=> CEDS-2097 Word and paragraph wrap for key and value

app/controllers/declaration/AdditionalFiscalReferencesController.scala, app/views/declaration/commodity_details.scala.html, conf/declaration.routes, test/views/declaration/CommodityDetailsViewSpec.scala
This bug was due to the behaviour of the 'fast-forward' functionality on the fiscal references (yes/no) page.  The fix was to change the default behaviour of fast-forward from true to false - the only scenario that needs FF is when coming back from the next page (post additional fiscal references)
=> CEDS-2084 - Change link for OSR should take the user to the correct page

app/views/declaration/summary/transport_section.scala.html, test/views/declaration/summary/TransportSectionViewSpec.scala
Removes the containers yes/no question when the answer is "yes".  The container summary section contains all links required to modify the containers/seals.  This solves the problem and is in line with the latest (v.29) prototype.
=> CEDS-2099 - container-change link on summary screen align with prototype

app/assets/javascripts/autocomplete.js
Gives the JQuery generated input field an id so that error message links correctly navigate to it
=> CEDS-1760 - Country error link does not target country input box

app/controllers/declaration/TransportContainerController.scala, app/views/declaration/summary/clearance_containers.scala.html, app/views/declaration/summary/transport_section.scala.html, app/views/declaration/transport_container_remove_clearance.scala.html, app/views/declaration/transport_container_summary_clearance.scala.html, test/unit/controllers/declaration/TransportContainerControllerSpec.scala, test/views/declaration/TransportClearanceContainerRemoveViewSpec.scala, test/views/declaration/TransportContainerRemoveClearanceViewSpec.scala, test/views/declaration/TransportContainerSummaryClearanceViewSpec.scala, test/views/declaration/summary/ClearanceContainersViewSpec.scala
* Skip `containers/container-id/seals` page
* The `back link` should not point to the seals page.
* Remove the Security seals column and the Change Seals from the
`/declaration/containers` page
* Do not show Seals info in the Summary page
=> CEDS-2039 Skip 'Security Seals' page for Clearance Declarations

app/forms/common/Eori.scala, app/forms/declaration/DeclarantDetails.scala, app/forms/declaration/DeclarationAdditionalActors.scala, app/forms/declaration/DeclarationHolder.scala, app/forms/declaration/EntityDetails.scala, app/views/declaration/summary/eori_or_address_section.scala.html, test/forms/declaration/DeclarationAdditionalActorsSpec.scala, test/forms/declaration/EntityDetailsSpec.scala, test/models/declaration/DeclarationHoldersDataSpec.scala, test/models/declaration/ExportDeclarationTestData.scala, test/services/cache/ExportsDeclarationBuilder.scala, test/unit/controllers/declaration/CarrierDetailsControllerSpec.scala, test/unit/controllers/declaration/ConsigneeDetailsControllerSpec.scala, test/unit/controllers/declaration/DeclarantDetailsControllerSpec.scala, test/unit/controllers/declaration/DeclarationAdditionalActorsControllerSpec.scala, test/unit/controllers/declaration/DeclarationHolderControllerSpec.scala, test/unit/controllers/declaration/ExporterDetailsControllerSpec.scala, test/unit/controllers/declaration/RepresentativeDetailsControllerSpec.scala, test/views/declaration/CarrierDetailsViewSpec.scala, test/views/declaration/ConsigneeDetailsViewSpec.scala, test/views/declaration/DeclarantDetailsViewSpec.scala, test/views/declaration/DeclarationAdditionalActorsViewSpec.scala, test/views/declaration/DeclarationHolderViewSpec.scala, test/views/declaration/ExporterDetailsViewSpec.scala, test/views/declaration/summary/AdditionalAndAuthorisedPartiesSectionViewSpec.scala, test/views/declaration/summary/EoriOrAddressSectionViewSpec.scala, test/views/declaration/summary/PartiesSectionViewSpec.scala
CEDS-2120 EORI is not accepted by DMS if it starts with lowercase letters
>lowercase to uppercase implemeantion for /additional-actors page
>lowercase to uppercase implemeantion for /holder-of-authorisation page
>Unit test case fixes
=> CEDS-2120: EORI is not accepted by DMS if it starts with lowercase letters

app/views/declaration/summary/transport_section.scala.html, test/services/cache/ExportsDeclarationBuilder.scala, test/views/declaration/summary/TransportSectionViewSpec.scala
that hadn't been asked.  Bug caused by transposing `meansOfTransportCrossingTheBorder` and `meansOfTransportOnDeparture`.  Bug only revealed by change that caused one of the pages to be skipped (they are normally both shown so the summary was correctly showing the answers to both pages).
=> BAU - fix for transport summary section where questions where shown

app/views/components/siteHeader.scala.html, app/views/govuk_wrapper.scala.html, conf/messages.en
A consistent naming convention must be displayed across all three CDS Exports services to provide users for a simplified experience and understanding.
The CDS Declarations Exports service was modified to:
1) the service name changed to CDS Exports in the banners at the top of each page,
2) the service name changed to CDS Exports on the start page.
=> CEDS-2057 - Rename the Export services

app/controllers/pdf/EADController.scala, app/services/ead/EADService.scala, app/views/pdf/pdfTemplate.scala.xml, conf/application.conf, conf/declaration.routes, conf/logback.xml, project/AppDependencies.scala, test/unit/base/ControllerSpec.scala, test/unit/controllers/pdf/EADControllerSpec.scala
* An Export Accompanying Document ('EAD') is a short summary in a
format agreed access the EU.
* A lorry driver needs to have a physical copy of an EAD with them
as they cross a border from the from an EU state to a non-EU state.
* Declarants need to be able to generate an EAD as a PDF, which they
can send electronically (or physically) to a driver.
**NOTE:**
This is a version using a XSL template.
@bambuchaAdm enjoyed https://pdfbox.apache.org/ API and is going to create an investigative spike to compare it. The test of fire will be once we have the final template with the DIS data
=> CEDS-2180 Generate PDF with 128-Barcode based on MRN

app/services/ead/EADService.scala
In the remote environments (development, QA and Staging) we are not able
to render the barcode due to a NullPointerException caused by the lack
of font configuration in our JRE-headless
```
java.lang.NullPointerException: null
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
```
We believe this is being caused by the fact that we were printing the
MRN as part of the barcode image. We hope that by removing the MRN from
the barcode image we will avoid this issue.
The line that fixes the issue is:
`code128Bean.setMsgPosition(HumanReadablePlacement.HRP_NONE)`
with …
=> CEDS-2180 Fix font configuration problem in QA/Dev

app/views/submissions.scala.html, test/views/SubmissionsViewSpec.scala
When no notifications have been received for a submission, change the default
on the submissions page from SubmissionStatus.UNKNOWN to SubmissionStatus.PENDING
=> CEDS-2211 - change submission status from 'Unknown' to 'Pending'

app/controllers/declaration/InlandTransportDetailsController.scala, app/controllers/declaration/SupervisingCustomsOfficeController.scala, app/controllers/navigation/Navigator.scala, test/unit/controllers/declaration/InlandTransportDetailsControllerSpec.scala, test/views/declaration/TransportLeavingTheBorderViewSpec.scala
For Clearance Requests, the '7/5 Inland Mode of Transport' data element is not required in any circumstances.
=> CEDS-2219 - Skip '7/5 Inland Mode of Transport' for Clearance Requests

app/views/declaration/representative_details.scala.html
FIXED wrong Back Button label.
The Representative Details page does not require Representative Name and Address. The Tariff Guidance does not require the corresponding reference as well.
=> CEDS-2234 - Improve 'Representative Details' screen

app/views/declaration/representative_details.scala.html
The pageTitle component uses a default govuk css style (defined in the 'Styles' constants).
The default style is currently slightly smaller than defined on the latest prototypes but it is consistent with the existing non-GDS pages.
By using the constants defined we can hopefully switch to the larger heading styled en-mass once all pages have been converted.
=> BAU - use the default govuk class for page heading

app/forms/declaration/CommodityDetails.scala, app/views/declaration/summary/item_section.scala.html, test/forms/declaration/CommodityDetailsSpec.scala, test/unit/controllers/declaration/CommodityDetailsControllerSpec.scala, test/views/declaration/CommodityDetailsViewSpec.scala, test/views/declaration/ItemSummaryViewSpec.scala, test/views/declaration/summary/ItemSectionViewSpec.scala
For Clearance Requests, data elements '6/14 Commodity code' and
'6/8 Description of Goods' are not required in the majority of cases.
This data element is not required on clearance requests using procedure
codes 00 18 or 00 19 in D.E. 1/10.
**Depends on: https://github.com/hmrc/customs-declare-exports/pull/169**
=> CEDS-2189 Make CommodityDetails.descriptionOfGoods optional

app/views/pdf/pdfTemplate.scala.xml, test/services/ead/EADServiceSpec.scala, test/unit/controllers/pdf/EADControllerSpec.scala
The EAD currently shows the ICS and Route (aka 'ROE').  This is no
longer required as there is a risk it may confuse other EU countries
who do not use these values.
=> CEDS-2269 Remove ICS & Route from the EAD

app/views/declaration/items_summary.scala.html, test/views/declaration/ItemSummaryViewSpec.scala
After changing package information fields to be optional they were
incorrectly presented on the items summary page. 'None' and 'Some' were
printed out to the screen.
Now, only the number is presented. If the value was left blank
(Clearance journey allows for that) nothing is presented on the page.
=> CEDS-2190 Fix items-summary page number of packages column

app/views/declaration/summary/warehouse_section.scala.html, conf/messages.en, test/views/declaration/summary/WarehouseSectionViewSpec.scala
CEDS-2277 specifies that the label on the summary screen should be "Warehouse" if the user answered "No" to the "Is in warehouse?" question
=> CEDS-2277 - warehouse summary label when user said "No"

app/views/declaration/declaration_additional_actors.scala.html
The constant value `Styles.gdsPageLegend` defines a smaller page heading style that is more consistent with the existing non-GDS pages and can be changed once all pages have been converted.
=> CEDS-2237 - use default GDS page heading style

app/controllers/declaration/DepartureTransportController.scala, app/controllers/declaration/TransportPaymentController.scala, app/controllers/navigation/Navigator.scala, test/unit/controllers/declaration/DepartureTransportControllerSpec.scala, test/unit/controllers/declaration/TransportPaymentControllerSpec.scala
There is currently no option for Declarants to add Transport Payment (data element 4/2) when completing a Clearance Request. Declarants should provide details of the transport payment when only for an EXS customs clearance request.
=> CEDS-2275 - Add Transport Payment screen into Clearance Request Journey

app/controllers/declaration/DeclarantDetailsController.scala, app/controllers/declaration/DispatchLocationController.scala, app/controllers/declaration/NotEligibleController.scala, app/forms/declaration/DeclarantDetails.scala, app/forms/declaration/DeclarantEoirConfirmation.scala, app/forms/declaration/DeclarantEoriConfirmation.scala, app/views/declaration/declarant_details.scala.html, app/views/declaration/not_declarant.scala.html, app/views/declaration/summary/parties_section.scala.html, conf/declaration.routes, conf/messages.en, docs/Customs Declare Exports AutoComplete.js, test/forms/declaration/DeclarantDetailsSpec.scala, test/forms/declaration/DeclarantEoriConfirmationSpec.scala, test/unit/controllers/declaration/DeclarantDetailsControllerSpec.scala, test/unit/controllers/declaration/DispatchLocationControllerSpec.scala, test/unit/controllers/declaration/NotEligibleControllerSpec.scala, test/views/declaration/DeclarantDetailsViewSpec.scala, test/views/declaration/summary/PartiesSectionViewSpec.scala
This PR changes the declarant EORI page from asking the user to enter their EORI to presenting them with the EORI from their login credentials and asking them to confirm it's correct.
I've not changed the cache model.  If the user confirms that the EORI is correct I copy it into the existing DeclarantDetails structure.
I've the user select's "No" they are logged out and shown a new "ineligible" page (content subject to change).
Finally, the declarant's EORI is presented on the summary screen as the first value in the Parties Section and the ability to 'change' has been removed.
=> CEDS-2064 - Declarant EORI

app/views/declaration/summary/parties_section.scala.html
There appears to be a bug with the govukfrontend  `SummaryList` component when rendering a row without a "Change" link.
The old code rendered an "illegal" empty `<span>` as a child of a `<dl>` - e.g.
```
<div class="govuk-summary-list__row declarant-eori-row">
<dt class="govuk-summary-list__key">
Your EORI number
</dt>
<dd class="govuk-summary-list__value">
GB717572504502811
</dd>
<span class="govuk-summary-list__actions"></span>
</div>
```
With the change, it renders an empty `<dd>` element - 
```
<div class="govuk-summary-list__row declarant-eori-row">
<dt class="govuk-summary-list__key">
Your EORI number
</dt>
<dd class="govuk-summary-list__value">
GB717572504502811
</dd>
<dd class="govuk-summary-list__actions">
<a class="govuk-link" href=""> </a>
</dd>
</div>
```
Well - one with an …
=> CEDS-2230 - fix for accessibility where there is no "change" link

app/controllers/declaration/TransportPaymentController.scala, test/unit/controllers/declaration/TransportPaymentControllerSpec.scala
Ensure SUPPLEMENTARY journey is not valid for the Transport Payment page.
There is currently no option for Declarants to add Transport Payment (data element 4/2) when completing a Clearance Request. Declarants should provide details of the transport payment when only for an EXS customs clearance request.
=> BAU-2275 - Add Transport Payment screen into Clearance Request Journey

app/assets/stylesheets/customsdecexfrontend-app.scss, app/assets/stylesheets/partials/_gdsBase.scss, app/assets/stylesheets/partials/_gdsSummaryLists.scss, app/views/components/fields/field_accessible_autocomplete.scala.html, app/views/components/gds/gdsMainTemplate.scala.html, app/views/components/inputs/input_accessible_autocomplete.scala.html, app/views/declaration/destinationCountries/change_routing_country.scala.html, app/views/declaration/destinationCountries/country_of_routing.scala.html, app/views/declaration/destinationCountries/destination_country.scala.html, app/views/declaration/destinationCountries/origination_country.scala.html, app/views/declaration/destinationCountries/remove_routing_country.scala.html, app/views/declaration/destinationCountries/routing_countries_summary.scala.html, app/views/declaration/destinationCountries/routing_country_question.scala.html, app/views/declaration/officeOfExit/office_of_exit_clearance.scala.html, app/views/declaration/officeOfExit/office_of_exit_standard.scala.html, app/views/declaration/officeOfExit/office_of_exit_supplementary.scala.html, docs/Customs Declare Exports AutoComplete.js, project/AppDependencies.scala, test/views/declaration/destinationCountries/ChangeRoutingCountryViewSpec.scala, test/views/declaration/destinationCountries/CountryOfRoutingViewSpec.scala, test/views/declaration/destinationCountries/DestinationCountryViewSpec.scala, test/views/declaration/destinationCountries/OriginationCountryViewSpec.scala, test/views/declaration/destinationCountries/RemoveRoutingCountryViewSpec.scala, test/views/declaration/destinationCountries/RoutingCountriesSummaryViewSpec.scala, test/views/declaration/destinationCountries/RoutingCountryQuestionViewSpec.scala, test/views/declaration/officeOfExit/OfficeOfExitClearanceViewSpec.scala, test/views/declaration/officeOfExit/OfficeOfExitStandardViewSpec.scala, test/views/declaration/officeOfExit/OfficeOfExitSupplementaryViewSpec.scala
This is the most tested library for an accessible dropdown/autocomplete
HTML input at GovUK: https://alphagov.github.io/accessible-autocomplete
This is the suggested approach taken by the HMRC CDS Exports prototype
and also recommended by @christophercameron-hmrc
This also includes rebuilding the following pages using GDS Design System:
* Routing Question page
* Routing Contries Summary page
* Remove Contry page
=> CEDS-2227 GDSfy Locations section including using accessible-autocomplete

app/controllers/declaration/OfficeOfExitController.scala, app/controllers/navigation/Navigator.scala, app/forms/declaration/officeOfExit/OfficeOfExit.scala, test/unit/controllers/declaration/OfficeOfExitControllerSpec.scala, test/views/declaration/PreviousDocumentsViewSpec.scala
The QA team found a couple of bugs:
1. When a Non-UK Office of Exit exists in cache and
we go back to the Office Of Exit page were overriding the Non-UK Office
of Exit data.
2. Fix back button for Simplified and Occasional journeys
=> CEDS-2366 Display cached Non-Uk Office of Exit

app/controllers/declaration/ConsigneeDetailsController.scala
Consignee page should only "short-cut" back to exporter details if declarant is the exporter and we are on supplementary journey.  Otherwise normal back navigation is required.
This perfectly illustrates what we discussed at the techtro today.
=> CEDS-2401 - fix for back link from consignee page when dec. is exporter

conf/application.conf
The 'timeout' parameter is the time before forced logout occurs - not the time the pop-up first appears.  So the user should be logged out after 15min of inactivity with a 2min warning
=> CEDS-2124 - Update timeoutDialog config

app/controllers/declaration/AdditionalInformationRequiredController.scala, app/views/declaration/summary/union_and_national_codes.scala.html
Because we weren't updating the items.additionalInformation state when submitting the Y/N answer on the first page, the default value of "None" meant that the section was never rendered.
The fix is to update the cache value to Some(AdditionalInformationData(Seq.empty)).   This is the same value as would be set if the user answered 'Y' but then did not provide any data on the next page.     So as it stands, we cannot differentiate between "N" and "Y" followed by no data - both will be rendered on the summary screen as "No".
However, as the AdditionalItems page needs re-writing to remove the old "add-to-list" pattern, I think this is OK for now.
=> CEDS-2383 - fix for correct display on summary screen

app/controllers/util/SubmissionDisplayHelper.scala, app/views/submissions.scala.html, test/controllers/util/SubmissionDisplayHelperSpec.scala
These are currently being displayed in all three tabs - Rejected, Actions Required and Other
They should only be in Other until their real status is determined.
=> CEDS-2387 - fix for submissions with pseudo status 'Pending'

app/views/declaration/summary/parties_section.scala.html
There was a bug related to no Change button for Declarant's EORI row if
it was the first row in the table.
This commit reverts the Declarant's EORI row to the previous
implementation.
=> CEDS-2400 Fix summary page parties section

app/models/declaration/notifications/Notification.scala, app/models/declaration/submissions/Action.scala, app/models/declaration/submissions/Submission.scala, app/views/ViewDates.scala, app/views/declaration_information.scala.html, app/views/notifications.scala.html, app/views/saved_declarations.scala.html, app/views/submission_notifications.scala.html, app/views/submissions.scala.html, test/base/MockConnectors.scala, test/connectors/CustomsDeclareExportsConnectorIntegrationSpec.scala, test/controllers/util/SubmissionDisplayHelperSpec.scala, test/models/declaration/notifications/NotificationSpec.scala, test/unit/controllers/NotificationControllerSpec.scala, test/unit/controllers/SubmissionsControllerSpec.scala, test/unit/services/model/RejectionReasonSpec.scala, test/views/DeclarationInformationViewSpec.scala, test/views/NotificationsViewSpec.scala, test/views/SavedDeclarationsViewSpec.scala, test/views/SubmissionsViewSpec.scala
DMS sends the times in UTC time, but our BE microservice converts them
to `LocalDateTime` which strips them of the Zone information.
Converting the type to `Instant` as we did in the the Movements service
allows us to store the date from DMS as `UTC` or `Zulu time` and then on
the FE we just need to inform the view that we want to render that time
on British Time Zone `Europe/London`.
This ensures that we will see the time as `GMT/UTC` and `BST` depending
on the time of the year.
This holds true as long as DMS returns their dates in UTC.
=> CEDS-2298 Display Time always on British time zone

app/controllers/declaration/ConsignorEoriNumberController.scala, app/forms/declaration/consignor/ConsignorEoriNumber.scala, test/unit/controllers/declaration/ConsignorEoriNumberControllerSpec.scala, test/unit/forms/declaration/consignor/ConsignorEoriNumberSpec.scala, test/views/declaration/ConsignorEoriNumberViewSpec.scala
This page must be mandatory.
Additionally I removed unnecessary controller spec cases plus added missing model spec.
I changed has eori to be not longer optional. This field always must be provided.
The hasEori field is not a part of the backend model, so those changes are compatible with current backend.
=> CEDS-2441 Make Consignor Eori mandatory

app/controllers/declaration/EntryIntoDeclarantsRecordsController.scala, test/unit/controllers/declaration/EntryIntoDeclarantsRecordsControllerSpec.scala
This is not to keep data that is unnecessary and potentially breaking
for downstream logic.
=> CEDS-2450 Remove PersonPresentingGoodsDetails if answered 'no' to EIDR

app/forms/common/Eori.scala, app/utils/validators/forms/FieldValidator.scala, conf/messages.en, test/unit/forms/declaration/consignor/ConsignorEoriNumberSpec.scala, test/utils/validators/forms/FieldValidatorSpec.scala
EORI is now validated according to the following:
- First 2 characters are letters (lower or upper case)
- Followed by 12-15 digits
=> CEDS-2439 Fix EORI validation

app/assets/javascripts/preventMultipleFormSubmissions.js, app/views/components/gds/gdsMainTemplate.scala.html
This was a problem when adding export items, where we could have added
50+ empty items, simply by clicking multiple times
There was also a problem on the summary page where we could submit the
final declaration multiple times.
=> CEDS-2478 Prevent multiple form submissions

app/assets/stylesheets/partials/_gdsBase.scss, app/views/declaration/summary/accepted_declaration_page.scala.html
From my experimentations I could not make Firefox read the `@page size`
property. According documentation only this is not yet a standard,
instead a few browsers support it, with Chrome being one of them.
=> CEDS-2509 Avoid breaking up secions when printing

app/views/rejected_notification_errors.scala.html
This is a fix for the error which appear for some decs on QA.
Error appear only when there is a list of mixed errors with and without url and the first notification doesn't have the url.
If there is a notification error list and it starts without error that contains the change url but next errors contains govukSummaryList try to get the url from non existing place which cause `None.get` error.
When the feature flag is enabled and notification error doesn't have the url we should still generate this column. This can be achieved with passing empty action list to summaryList component
=> BAU Add empty action when the feature flag is enabled

app/controllers/SubmissionsController.scala
This will fix the bug where the declaration id is in the users session after viewing completed declaration.   Providing the user navigates back to the choice page using the back links.
=> CEDS-2538 - remove declaration id from session when viewing submissions

app/views/components/gds/ActionItemBuilder.scala, app/views/declaration/summary/EoriOrAddress.scala, app/views/declaration/summary/containers.scala.html, app/views/declaration/summary/countries_section.scala.html, app/views/declaration/summary/item_section.scala.html, app/views/declaration/summary/locations_section.scala.html, app/views/declaration/summary/package_information.scala.html, app/views/declaration/summary/parties_section.scala.html, app/views/declaration/summary/parties_section_additional_actors.scala.html, app/views/declaration/summary/parties_section_holders.scala.html, app/views/declaration/summary/references_section.scala.html, app/views/declaration/summary/related_documents.scala.html, app/views/declaration/summary/supporting_documents.scala.html, app/views/declaration/summary/transaction_section.scala.html, app/views/declaration/summary/transport_section.scala.html, app/views/declaration/summary/union_and_national_codes.scala.html, app/views/declaration/summary/warehouse_section.scala.html, app/views/rejected_notification_errors.scala.html
Noticed on the summary page(s) that the "change" links were not showing the correct "visited" state.  (They were showing as "purple" for visited links - there shouldn't be any difference in appearance between visited and non-visited links).
These change links are created by the govukfrontend `ActionItem` class so I've created a little "builder" class to construct one of those with the appropriate css class.
=> BAU - action link item with correct govuk css class

app/views/declaration/summary/related_documents.scala.html
Nothing to do with the 2-step changes
=> CEDS-2493 - fix layout of previous documents in CYA summary page

app/controllers/declaration/AdditionalInformationRemoveController.scala, app/controllers/declaration/AdditionalInformationRequiredController.scala, app/controllers/navigation/Navigator.scala, test/unit/controllers/declaration/AdditionalInformationRemoveControllerSpec.scala, test/unit/controllers/declaration/AdditionalInformationRequiredControllerSpec.scala, test/views/declaration/AdditionalInformationViewSpec.scala
Two changes
1. After removing the last item from the list, redirect back to the "Do you want to add?" screen rather than the summary controller which then re-directs to the "Add" page
2. Only display the "Do you want to add?" page if there are no items in the cache.  This makes the backwards/forwards navigation more logical for users.
=> CEDS-2561 - Change navigation behaviour for "Additional Information"

app/assets/stylesheets/partials/_currency_input.scss, app/assets/stylesheets/partials/_gdsBase.scss, app/views/components/gds/exportsInputTextWithPrefix.scala.html, app/views/declaration/additionalActors/additional_actors_add.scala.html, app/views/declaration/cus_code.scala.html, app/views/declaration/un_dangerous_goods_code.scala.html
Fixes some of the minor issues identified in CEDS-2529
- size of auto-complete text
- position of currency character within input field
- width of input fields for CUS and UN codes
=> CEDS-2529 - auto-complete font size

app/controllers/declaration/ItemsSummaryController.scala, test/unit/controllers/declaration/ItemsSummaryControllerSpec.scala
After removing an item we need to check if any of the remaining items contain a procedure code that would require the user to enter a warehouse id.  If there are none, then we remove any previously supplied warehouse answer as that question will now be skipped.
=> CEDS-2537 - remove warehouse answer when removing item

app/controllers/declaration/ProcedureCodesController.scala, test/unit/controllers/declaration/ProcedureCodesControllerSpec.scala
The bug was that I was checking if any item had a "warehouse required" procedure code _before_ applying the changed procedure code.    So changing from a WH-required to non-WH-required was failing to remove the WH data.
=> CEDS-2537 - fix bug with changing proc code from WH to non-WH required

app/views/declaration/additional_fiscal_references.scala.html, app/views/declaration/procedure_codes.scala.html, app/views/saved_declarations.scala.html, test/views/SavedDeclarationsViewSpec.scala, test/views/declaration/AdditionalActorsSummaryViewSpec.scala, test/views/declaration/AdditionalFiscalReferencesViewSpec.scala, test/views/declaration/AdditionalInformationViewSpec.scala, test/views/declaration/DeclarationHolderSummaryViewSpec.scala, test/views/declaration/DocumentsProducedViewSpec.scala, test/views/declaration/NactCodesViewSpec.scala, test/views/declaration/PackageInformationViewSpec.scala, test/views/declaration/PreviousDocumentsSummaryViewSpec.scala, test/views/declaration/ProcedureCodesViewSpec.scala, test/views/declaration/SealSummaryViewSpec.scala, test/views/declaration/TaricCodesViewSpec.scala, test/views/declaration/TransportContainerSummaryViewSpec.scala, test/views/declaration/declarationitems/ItemsSummaryViewSpec.scala, test/views/declaration/summary/ContainersViewSpec.scala, test/views/declaration/summary/PackageInformationViewSpec.scala, test/views/declaration/summary/PartiesSectionAdditionalActorsViewSpec.scala, test/views/declaration/summary/PartiesSectionHoldersViewSpec.scala, test/views/declaration/summary/RelatedDocumentsViewSpec.scala, test/views/declaration/summary/SupportingDocumentsViewSpec.scala, test/views/declaration/summary/UnionAndNationalCodesViewSpec.scala
Use visually hidden header for 'Remove' link column on the following tables:
- procedure-codes
- saved-declarations
- additional-fiscal-references
=> CEDS-2595 Accessibility: empty table headers

app/assets/stylesheets/partials/_autocomplete.scss, app/assets/stylesheets/partials/_exports.scss, app/assets/stylesheets/partials/_lists.scss
Same fix for dashed list (contents) on start page
Auto-complete drop-down arrow top relative to font size
=> CEDS-2612 - remove fixed font size for "more info" sections

app/views/declaration/summary/amend_summary_page.scala.html, app/views/declaration/summary/draft_summary_page.scala.html, app/views/declaration/summary/normal_summary_page.scala.html, app/views/declaration/summary/submitted_declaration_page.scala.html, app/views/declaration/summary/summary_page_no_data.scala.html
This change is to make Summary pages more accessible when used with
double-sized font.
Many words were split into multiple lines which was an issue.
=> CEDS-2614 Change Summary pages to full width

app/assets/stylesheets/partials/_shame.scss
This solution reduces font so that the text fits inside the panel before
switching into mobile mode.
Special thanks to @russellthorn for his help.
=> CEDS-2678 Fix issue with text overflowing in panel on confirmation page

app/services/model/RejectionReason.scala, conf/code-lists/errors-dms-rej-list.csv, test/unit/services/model/RejectionReasonSpec.scala
In some instances the WCO Declaration pointer will be returned but it
can map to two different pages on our user journey, which is depending on the
declaration type and the questions answered.
This means that we need to dynamically send the user to the correct page
based on the above.
This is an approach that keep the responsibility of this task/decision
in the RejectionReason class.
=> CEDS-2755 Add a Pointer Based URL logic

app/controllers/util/MultipleItemsHelper.scala, app/views/components/gds/formGroupWrapper.scala.html, test/controllers/util/MultipleItemsHelperSpec.scala, test/views/components/gds/FormGroupWrapperSpec.scala
This PR is a preparation for CEDS-2768.
Because it is not a functional change I decided to do it as "BAU".
The component simply allows to wrap any html content and
provides an option to give it an id. This is done in order to handle
form errors.
The second part is a small change to MultipleItemsHelper, to allow
the client to provide the field id that will have `FormErrors` 
associated with it.
=> BAU form group wrapper component

app/controllers/declaration/AdditionalInformationChangeController.scala, app/controllers/declaration/DeclarationHolderChangeController.scala, app/controllers/declaration/DocumentsProducedChangeController.scala, app/controllers/declaration/PreviousDocumentsChangeController.scala, app/views/declaration/documentsProduced/documents_produced_edit_content.scala.html
Remove commas from Additional Documentation page.
Include field ID on Change controllers for the following pages:
- /add-previous-documents, 
- /additional-documentation, 
- /add-authorisation-required, 
- /additional-information.
=> CEDS-2768 Update duplication errors on multiple field pages

app/controllers/navigation/Navigator.scala
After splitting carrier details into two pages the Navigator logic
was incorrectly modified and left out some required checks.
=> [CEDS-2758] Fix back button flow on clearance journey

app/controllers/declaration/AdditionalActorsAddController.scala, app/controllers/declaration/AdditionalFiscalReferencesAddController.scala, app/controllers/declaration/AdditionalInformationAddController.scala, app/controllers/declaration/AdditionalInformationChangeController.scala, app/controllers/declaration/DeclarationHolderAddController.scala, app/controllers/declaration/DeclarationHolderChangeController.scala, app/controllers/declaration/DocumentsProducedAddController.scala, app/controllers/declaration/DocumentsProducedChangeController.scala, app/controllers/declaration/NactCodeAddController.scala, app/controllers/declaration/PackageInformationAddController.scala, app/controllers/declaration/PreviousDocumentsChangeController.scala, app/controllers/declaration/PreviousDocumentsController.scala, app/controllers/declaration/SealController.scala, app/controllers/declaration/TaricCodeAddController.scala, app/controllers/declaration/TransportContainerController.scala, app/controllers/util/MultipleItemsHelper.scala, conf/messages.en, test/controllers/util/MultipleItemsHelperSpec.scala
Customise the duplicate items error messages to be specific to the
elements/context in which they are triggered.
Previously the error message "You cannot add duplicated value."
was used in all instances where multiple elements could be
specified on a declaration journey. Now we have specific messages
crafted by James Watson for each element.
=> [CEDS-2769] Update duplication error messages

app/config/AppConfig.scala, app/views/components/gds/phaseBanner.scala.html, conf/application.conf, test/config/AppConfigSpec.scala, test/unit/controllers/declaration/CarrierDetailsControllerSpec.scala, test/views/components/gds/PhaseBannerSpec.scala, test/views/declaration/CarrierEoriNumberViewSpec.scala, test/views/declaration/fiscalInformation/FiscalInformationViewSpec.scala
There are 2 issues that are fixed in this PR:
1. `backURL` should have capitalized 'URL'
2. In other environments, the link to contact-frontend was incorrect.
It should be using url, similarly to how we link to Movements in
Declarations service.
=> CEDS-2668 Fix contact-frontend url

run-contact-frontend-sm_local.sh
This script runs contact-frontend service and provides Exports UI
frontend services to its backUrlDestinationWhitelist. This is to allow
for backUrl functionality.
=> CEDS-2668 Add script to start contact-frontend service

app/views/declaration/dispatch_location.scala.html
=> CEDS-2919 Make question/legend H1 to correct DAC failure issue

app/forms/declaration/CommodityDetails.scala, app/views/components/gds/exportsInputCharacterCount.scala.html, app/views/declaration/commodity_details.scala.html
The current implementation fails WCAG single A legal requirements because the character limit is not announced at any point or that you have exceeded the count limit. You are only presented with a page error if you exceed the count. The GOV.UK component addresses all these issues and fixes them https://design-system.service.gov.uk/components/character-count/
=> CEDS 2926 update character count to use GOV.UK accessible component

app/assets/stylesheets/partials/_shame.scss, app/views/components/gds/phaseBanner.scala.html, app/views/components/gds/saveAsDraft.scala.html, app/views/declaration/additionalInformtion/additional_information_edit_content.scala.html, app/views/declaration/additionalInformtion/additional_information_required.scala.html, app/views/declaration/cus_code.scala.html, app/views/declaration/documentsProduced/documents_produced_edit_content.scala.html, app/views/declaration/nact_code_add.scala.html, app/views/declaration/nact_code_add_first.scala.html, app/views/declaration/not_eligible.scala.html, app/views/declaration/taric_code_add.scala.html, app/views/declaration/taric_code_add_first.scala.html, app/views/declaration/un_dangerous_goods_code.scala.html, test/views/RejectedNotificationErrorsViewSpec.scala, test/views/declaration/summary/SubmittedDeclarationPageViewSpec.scala
Also done:
- updated CSS for the Save and come back later button styled as a link, so the focus state complies to recommended standards
=> CEDS-2931 Add govuk-link class to all links to correct colour styling

app/config/SfusConfig.scala, app/views/declaration_information.scala.html, conf/application.conf, test/views/DeclarationInformationViewSpec.scala
As part of the usability improvements we are allowing the link
to SFUS from the Exports UI to include the MRN of the declaration
to pre-populate that field and remove the need for the user
to re-type it.
=> [CEDS-2821] Receiving MRN via URL param to skip entry page

app/views/user_signed_out.scala.html, conf/messages.en
Will be brought back once the Government Gateway link
has been created.
=> [CEDS-2965] Removing signin link from signout page

app/controllers/ChoiceController.scala, app/forms/Choice.scala, app/views/choice_page.scala.html, conf/application.conf, conf/messages.en, test/base/ExportsTestData.scala, test/unit/controllers/ChoiceControllerSpec.scala, test/unit/controllers/actions/AuthActionSpec.scala, test/views/ChoiceViewSpec.scala
Add a new radio button option that when selected takes
the user to the Exports secure message inbox page, only
visible when the 'secureMessagingInbox' feature flag is
set to 'exports'.
Also adds a link to the SFUS file upload service on the
choice page when 'secureMessagingInbox' feature flag is
set to 'exports'.
=> [CEDS-3109]_Choice_page_for_Exports_UI

app/forms/common/Address.scala, conf/messages.en, test/forms/common/AddressSpec.scala, test/forms/declaration/EntityDetailsSpec.scala, test/unit/forms/declaration/ExporterDetailsSpec.scala
Before the address form validation restricted values
to be alphanumeric and latin characters only.
This is in contrast to the DMS Schema rules that allow
any characters and only limits on the field lengths
allowed.
These changes relax the implemented validation rules
to become inline with the DMS Schema rules.
=> [CEDS-2879] Make address validation more permissive

conf/app.routes
This is a fix to cover for hardcoded url value
in secure-message-frontend partial always pointing
to /messages url.
=> CEDS-3058 Change inbox endpoint to /messages

app/services/DocumentType.scala, test/services/DocumentTypeSpec.scala
Set order of document types on 'previous_documents' page as shown at the gov.uk link given in ticket
=> CEDS-3132 Set order of document types on 'previous_documents' page

app/assets/javascripts/timeoutDialog.js
This file is not needed for timeout to work correctly.
=> BAU Remove timeoutDialog.js file

app/controllers/declaration/AdditionalProcedureCodesController.scala, app/models/codes/AdditionalProcedureCode.scala, conf/messages.en, test/controllers/declaration/AdditionalProcedureCodesControllerSpec.scala
Don't allow '000' if another code already exists and
don't allow another code if '000' already exists.
=> [CEDS-3203] New validation rules for handling APC 000

app/controllers/declaration/RepresentativeAgentController.scala, test/controllers/declaration/RepresentativeAgentControllerSpec.scala
Logic was wrong way around so it cleared the EORI if user
selected that they were not the representative (instead of
the other way around as it should be).
=> [CEDS-3291] Bug fix Representatives EORI being lost from cache

app/controllers/declaration/AdditionalProcedureCodesController.scala, test/base/ControllerSpec.scala, test/controllers/declaration/AdditionalProcedureCodesControllerSpec.scala
000 validation was only being applied when the user pressed the
"Add" button. This was due to two different validation routines
depending on which button was used to submit the form.
Now implemented single validation routine used for all form submit
buttons on page. Also updated tests to include the "Save for later"
form action.
=> [CEDS-3203] Fix validation not applying on save and continue

app/controllers/declaration/AdditionalProcedureCodesController.scala, app/controllers/declaration/ModelCacheable.scala, app/controllers/util/SupervisingCustomsOfficeHelper.scala
Fix a caching problem with the APC page when not clicking the 'Add' button but directly clicking the 'Save and continue' button.
=> CEDS-3246 Fix a caching problem with the APC page

app/forms/CancelDeclaration.scala, app/forms/declaration/GoodsLocationForm.scala, app/forms/declaration/additionaldocuments/AdditionalDocument.scala, test/forms/CancelDeclarationSpec.scala, test/forms/declaration/AdditionalDocumentSpec.scala, test/forms/declaration/GoodsLocationFormSpec.scala, test/views/declaration/DeclarationHolderAddViewSpec.scala
Auto trim strings on certain fields so that users do not need
to worry if they accidentally paste a white space char at the
beginning or end of a value
=> [CEDS-3131] Trim white spaces

app/controllers/declaration/ConsignmentReferencesController.scala, app/forms/declaration/ConsignmentReferences.scala, app/views/declaration/consignment_references.scala.html, test/controllers/declaration/ConsignmentReferencesControllerSpec.scala, test/forms/declaration/ConsignmentReferencesSpec.scala, test/views/declaration/ConsignmentReferencesViewSpec.scala
New MRN field should only be displayed for SUPPLEMENTARY_SIMPLIFIED
additional declaration types (not for SUPPLEMENTARY_EIDR journeys!)
=> [CEDS-3292] Limit to just SDP Journeys

app/controllers/declaration/ConsignmentReferencesController.scala
The DUCR entered by the user must not be removed from the page in case the pair EORI-DUCR is already present in the Submissions collection. While showing the error message `DUCR already submitted` the DUCR must be retained on the page.
=> CEDS-3407 Fix the erroneous removal of DUCR from the 'Consignment References' page

app/views/declaration/additionalDocuments/additional_document_add.scala.html, app/views/declaration/additionalDocuments/additional_document_change.scala.html, app/views/declaration/additionalDocuments/additional_document_edit.scala.html, app/views/declaration/declarationHolder/declaration_holder_edit_content.scala.html, app/views/declaration/declarationHolder/declaration_holder_required.scala.html, app/views/helpers/AdditionalDocument.scala, app/views/helpers/DeclarationHolder.scala, app/views/helpers/TimelineEvents.scala, test/views/helpers/TimelineEventsSpec.scala
Change a few template helpers to singleton classes in order to inject the component/partial instances used, instead of creating new ones at every call.
=> BAU Change a few template helpers to singleton classes

app/views/components/gds/gdsMainTemplate.scala.html, test/tools/Stubs.scala
Removing duplicate tracking consent script from the layout:
This is called in the HmrcHead now, so no need for a standalone reference unless user is no longer signed in.
=> CEDS-3484 - Removed duplicate tracking consent reference

app/views/components/gds/gdsMainTemplate.scala.html
Removing an unnecessary type attribute - should remove 200 lines of INFO from the VNU/AXE testing report.
Also a tiny bit of tidy up around that block.
=> CEDS-3485 - Removed superfluous type attribute

app/views/unverified_email.scala.html, conf/messages.en
Just a small amendment to the previous PR where I had missed the exact wording for the unverified email page.
True wording here: https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=267126114
=> CEDS-3488 Handling undeliverable / unverified email addresses (Exports UI)

conf/code-lists/dmsErrorCodes-customised.json, conf/messages.en
Also add a missing error description text.
=> [BAU] Remove typos from error code titles

app/forms/declaration/Document.scala, app/forms/declaration/additionaldocuments/AdditionalDocument.scala, app/utils/validators/forms/FieldValidator.scala, app/views/helpers/PreviousDocumentsHelper.scala, conf/messages.en, test/forms/declaration/DocumentSpec.scala, test/views/declaration/previousDocuments/PreviousDocumentsViewSpec.scala
In addition, `hint` is now unified for versions 3-5.
=> CEDS-3553 Non-consecutive blanks now accepted for 'Document reference' on page at '/add-previous-document'

app/controllers/helpers/SupervisingCustomsOfficeHelper.scala, app/controllers/navigation/Navigator.scala, app/models/ExportsDeclaration.scala, docs/Customs Declare Exports AutoComplete.js, test/controllers/UnverifiedEmailControllerSpec.scala, test/controllers/helpers/SupervisingCustomsOfficeHelperSpec.scala, test/services/cache/ExportsDeclarationBuilder.scala, test/views/declaration/ExpressConsignmentViewSpec.scala
Skip the /departure-transport page if user enters
'Fixed transport installation' OR 'Postal'
on /transport-leaving-the-border page.
Also fixing the AutoComplete.js for dec type choice page.
=> [CEDS-3614] Skip conditionality for C21 FTI and postal

conf/application.conf
To meet splunk storage requirements.
=> CEDS-3650 Add config to stop asset request auditing

app/config/featureFlags/TdrUnauthorisedMsgConfig.scala, app/controllers/actions/AuthAction.scala, app/views/unauthorised.scala.html, conf/application.conf, conf/messages.en, test/base/MockAuthAction.scala, test/config/featureFlags/TdrUnauthorisedMsgConfigSpec.scala, test/controllers/ChoiceControllerSpec.scala, test/controllers/actions/AuthActionSpec.scala, test/controllers/declaration/SummaryControllerSpec.scala, test/views/UnauthorisedViewSpec.scala, test/views/declaration/ExpressConsignmentViewSpec.scala, test/views/declaration/confirmation/ConfirmationViewSpec.scala
Also prevent users who are not logged in from hitting an Exports page
and causing an ERROR level log output (that triggers PagerDuty alerts).
=> [CEDS-3628] Prevent user in TDR from trying to register for CDS

app/forms/declaration/additionaldocuments/AdditionalDocument.scala, app/views/components/gds/errorSummary.scala.html, app/views/helpers/InputTextHelper.scala, conf/messages.en, test/views/declaration/AdditionalDocumentEditViewSpec.scala, test/views/declaration/spec/ViewMatchers.scala
Adding of temporary error message stopping use of code "Y999"
Had to enable escaping of HTML in a couple of places to allow for this multi-line error message.
=> CEDS-3577 Add error message for Y999 doc code

app/controllers/declaration/InlandOrBorderController.scala, app/controllers/declaration/InlandTransportDetailsController.scala, app/controllers/declaration/SupervisingCustomsOfficeController.scala, app/controllers/declaration/TransportLeavingTheBorderController.scala, app/controllers/declaration/WarehouseIdentificationController.scala, app/controllers/helpers/InlandOrBorderHelper.scala, app/models/ExportsDeclaration.scala, test/controllers/declaration/InlandOrBorderControllerSpec.scala, test/controllers/declaration/SupervisingCustomsOfficeControllerSpec.scala, test/controllers/declaration/TransportLeavingTheBorderControllerSpec.scala, test/controllers/declaration/WarehouseIdentificationControllerSpec.scala
1. Clear out any cached value on /inland-transport-details when the user selects 'border' on /inland-or-border.
2. Clear out any cached value on /inland-or-border when the user submits (POST) /transport-leaving-the-border.
=> CEDS-3771 When required, clear values cached from /inland-transport-details and /inland-or-border

app/controllers/declaration/CommodityDetailsController.scala, app/forms/declaration/CommodityDetails.scala, app/utils/validators/forms/FieldValidator.scala, app/views/declaration/commodity_details.scala.html, conf/messages.en, test/forms/declaration/CommodityDetailsSpec.scala, test/views/declaration/CommodityDetailsViewSpec.scala
Also amend content of the /commodity-details page
=> CEDS-3696 Allow 8-digits Commodity codes, in addition to 10-digits ones

app/controllers/declaration/DepartureTransportController.scala, app/controllers/navigation/Navigator.scala, test/controllers/declaration/DepartureTransportControllerSpec.scala, test/views/declaration/TransportCountryViewSpec.scala
Amend STANDARD and SUPPLEMENTARY journeys skipping /border-transport when user selects 'Border' on /inland-or-border
=> CEDS-3794 Amend STANDARD and SUPPLEMENTARY journeys

app/controllers/actions/AuthAction.scala, app/controllers/declaration/DeclarationHolderSummaryController.scala, app/forms/declaration/declarationHolder/AuthorizationTypeCodes.scala, app/services/view/HolderOfAuthorisationCodes.scala, test/base/ExportsTestData.scala, test/base/MockAuthAction.scala, test/controllers/actions/AuthActionSpec.scala, test/controllers/declaration/DeclarationHolderSummaryControllerSpec.scala
Previously there were instances where an Agent could potentially see another type of unauthorised page, not the one intended for them. This ensures Agents see the agent kick out regardless of any other auth data values.
=> CEDS-3855 Ensure that Agents accessing service see agent-kick-out

app/forms/declaration/ConsigneeDetails.scala, app/forms/declaration/NactCode.scala, app/forms/declaration/TaricCode.scala, app/forms/declaration/carrier/CarrierDetails.scala, app/forms/declaration/consignor/ConsignorDetails.scala, test/forms/declaration/PartiesSpec.scala
Fix Taric code pointer to point to 'taricCode'
Fix National Additional code pointer to point to 'nactCode' 
Fix CarrierDetails pointer to not repeat 'carrierDetails' part of pointer 
Fix ConsigneeDetails pointer to not repeat 'consigneeDetails' part of pointer 
Fix ConsignorDetails pointer to not repeat 'consignorDetails' part of pointer
=> CEDS-4787 DEV: Fix issues with DiffTool producing incorrect pointers

app/views/helpers/TimelineEvents.scala, test/views/helpers/TimelineEventsSpec.scala
The problem was due to the fact that the `NotificationSummary.dateTimeIssued` value has no milliseconds defined, where as the `Action.requestTimestamp` does have milliseconds.
To correctly render events on the timeline page we create a 'fake' amendment request event, and set it's dateTime value to equal the `Action.requestTimestamp` value (that includes milliseconds).
However the amendment notification we receive back from DMS (the `NotificationSummary.dateTimeIssued` value) has no milliseconds value (so its effective value is '000'ms).
So when the 2 events are sorted the 'fake' request event (based on the `Action.requestTimestamp`) always appears chronologically later than the actual notification event (based on the `NotificationSummary.dateTimeIssued`). Obviously the request event …
=> CEDS-4772 Fix of incorrect display order on the Timeline page for rejected amendments

README.md, app/config/AppConfig.scala, app/controllers/actions/AuthAction.scala, app/utils/GenerateTdrSecret.scala, app/utils/HashingUtils.scala, conf/application.conf, conf/messages, project/AppDependencies.scala, test/base/ExportsTestData.scala, test/base/MockAuthAction.scala, test/config/AppConfigSpec.scala, test/controllers/ChoiceControllerSpec.scala, test/controllers/actions/AuthActionSpec.scala, test/views/UnauthorisedEoriViewSpec.scala
Adding new 'secret.tdrHashSalt' config value that will only be set in the TDR environment.
Adding additional authentication check that if the 'tdrHashSalt' value is present in config, then the user must specify an additional HMRC-CUS-ORG enrolment value of 'TDRSecret' who's value must be a valid hash of the supplied 'EORINumber' value.
Also removing redundant legacy appconfig values: "allowList.shutterPage", "allowList.ips","allowList.excludedPaths" & "allowList.enabled"
=> CEDS-4812 Secure Exports FE login on TDR with additional secret value

README.md, app/utils/GenerateTdrSecret.scala
To allow supplying multiple EORIs in a single run
=> BAU Altering TDRSecret generator program

app/handlers/ErrorHandler.scala, app/services/SubmissionService.scala, app/services/audit/AuditService.scala, test/controllers/DeclarationDetailsControllerSpec.scala, test/mock/ErrorHandlerMocks.scala, test/services/SubmissionServiceSpec.scala, test/services/audit/AuditServiceSpec.scala
Altering amend audit event to match format agreed with the CIP team.
Also fixing bug found that resulted in empty page being rendered to user on internal error scenario. Fix to show standard service 'sorry' page.
=> CEDS-4834 amend cip preparing an audit event payload for amend functionality

conf/application.conf, test/config/AppConfigSpec.scala, test/config/featureFlags/FeatureSwitchConfigSpec.scala
Reverts hmrc/customs-declare-exports-frontend#1846
=> Revert "CEDS-4880: disable use-improved-error-messages feature"

conf/application.conf, project/plugins.sbt
Adding in settings for GA4 plus general review to comply with standards: https://confluence.tools.tax.service.gov.uk/display/SEC/Content+Security+Policy+Guidance
=> CEDS-5089 GA4 Update the Content Security Policy

app/connectors/CustomsDeclareExportsConnector.scala, app/services/AuditCreateDraftDec.scala
Fix bug where the audit event was firing prematurely for new draft decs before the DUCR was set
=> CEDS-5205 Add new event on draft dec creation - fix bug

app/controllers/ErrorsReportedController.scala, test/controllers/ErrorsReportedControllerSpec.scala
Prior to fix, when user clicked "Change" link to address the error, the system was erroneously creating a DRAFT dec instead of an AMENDMENT_DRAFT
=> CEDS-5528 Bugfix on rejected amendments when using new error report page

app/connectors/CustomsDeclareExportsConnector.scala
By removing call to explicitlyIncludeHeaders that should only be used for calls to systems external to the MDTP platform.
=> CEDS-6075 Remove duplicate X-Request-Id values in CIP logs

app/views/section6/container_add.scala.html
Remove 'More Details' link from 'What is the Container ID?' page.
=> DCWL-3295 - Remove 'More Details' link
